
'use server';

import { revalidatePath } from 'next/cache';
import { auditService } from '@/backend/services/audit.service';
import { getCurrentUserId } from '@/backend/utils/auth';
import type { SubdomainApplication, User } from '@/backend/models/types';
import { 
  createApplication, 
  updateApplicationStatus, 
  getApplicationById, 
  createDomainFromApplication 
} from '@/backend/services';

type ActionResponse = {
  success: boolean;
  message: string;
}

// Helper function for logging activity
const logActivity = async (action: string, description: string, userRole: string) => {
  await auditService.logAction({
    action,
    resourceType: 'application',
    resourceId: 'system',
    description,
    userId: 'system',
    userRole
  });
};

export async function submitApplication(applicationData: Omit<SubdomainApplication, 'id' | 'status' | 'submittedDate' | 'documents'>, currentUserRole: User['role']): Promise<ActionResponse> {
  const { domainName, applicantName, opd, description } = applicationData;

  if (!domainName || !applicantName || !description || !opd) {
    return { success: false, message: 'Data tidak lengkap.' };
  }

  try {
    const newApplication: SubdomainApplication = {
      ...applicationData,
      id: '', // Will be generated by createApplication
      status: 'pending_review' as const,
      submittedDate: new Date().toISOString().split('T')[0],
      documents: ['surat_permohonan.pdf'], // Placeholder
    };
    
    const newAppId = await createApplication(newApplication);
    
    const currentUserId = await getCurrentUserId();
    
    await auditService.logAction({
      action: 'SUBMIT_APPLICATION',
      resourceType: 'application',
      resourceId: newAppId,
      description: `Mengajukan permohonan untuk ${domainName}`,
      userId: currentUserId?.toString() || 'unknown',
      user: applicantName,
      userRole: currentUserRole
    });

    revalidatePath('/applications');
    revalidatePath('/dashboard');
    revalidatePath('/super-admin/dashboard');
    
    return { 
      success: true, 
      message: 'Permohonan berhasil dikirim untuk ditinjau.',
    };
  } catch (error) {
    console.error('Error submitting application:', error);
    return { success: false, message: 'Terjadi kesalahan pada server saat memproses permohonan.' };
  }
}

export async function forwardForApproval(applicationId: string, currentUserRole: User['role']): Promise<{ success: boolean; message: string }> {
  const allowedRoles: User['role'][] = ['Super Admin', 'Pengelola Sistem'];
  if (!allowedRoles.includes(currentUserRole)) {
    return { success: false, message: 'Anda tidak memiliki izin untuk melakukan tindakan ini.' };
  }

  try {
    const application = await getApplicationById(applicationId);
    if (!application) {
      throw new Error('Application not found');
    }
    
    await updateApplicationStatus(applicationId, 'pending_approval');
    
    logActivity('FORWARD_FOR_APPROVAL', `Meneruskan permohonan ${applicationId} (${application.domainName}) untuk persetujuan final.`, currentUserRole);
    
    revalidatePath('/applications');
    revalidatePath(`/applications/${applicationId}`);
    revalidatePath('/super-admin/dashboard');
    revalidatePath('/audit-trail');

    return { success: true, message: `Permohonan ${applicationId} berhasil diteruskan untuk persetujuan final.` };
  } catch (error) {
    console.error('Error forwarding application:', error);
    return { success: false, message: 'Terjadi kesalahan saat meneruskan permohonan.' };
  }
}


export async function approveApplication(applicationId: string, currentUserRole: User['role']): Promise<{ success: boolean; message: string }> {
  const allowedRoles: User['role'][] = ['Administrator', 'Kepala Bidang'];
  if (!allowedRoles.includes(currentUserRole)) {
    return { success: false, message: 'Anda tidak memiliki izin untuk melakukan tindakan ini.' };
  }

  try {
    const application = await getApplicationById(applicationId);
    if (!application) {
      throw new Error('Application not found');
    }
    
    await updateApplicationStatus(applicationId, 'approved');
    
    // Only create domain if it's a subdomain application
    if ('domainName' in application) {
      const domain = await createDomainFromApplication(application as SubdomainApplication);
      
      // Auto-create DNS records if provider is configured
      if (domain) {
        try {
          const { dnsManagerService } = await import('@/backend/services/dns/dns-manager.service');
          
          const currentUserId = await getCurrentUserId();
          const userId = currentUserId?.toString() || 'system';
          
          // Get target IP from environment or use default
          const targetIP = process.env.DEFAULT_SERVER_IP || '103.xxx.xxx.xxx';
          
          const dnsResult = await dnsManagerService.createDomainRecords({
            domain: domain as any, // ServiceDomain to Domain type compatibility
            targetIP,
            createWWW: true,
            proxied: true,
            userId,
          });
          
          if (!dnsResult.success) {
            console.warn(`DNS creation warning for ${domain.hostname}:`, dnsResult.error);
            // Don't fail the approval, just log the warning
            await auditService.logAction({
              action: 'DNS_AUTO_CREATE_WARNING',
              resourceType: 'domain',
              resourceId: domain.id.toString(),
              description: `DNS auto-create warning: ${dnsResult.error}. Domain created but DNS may need manual configuration.`,
              userId,
              userRole: currentUserRole
            });
          }
        } catch (dnsError) {
          console.error('Error auto-creating DNS records:', dnsError);
          // Don't fail the approval, just log the error
          await auditService.logAction({
            action: 'DNS_AUTO_CREATE_ERROR',
            resourceType: 'domain',
            resourceId: domain.id.toString(),
            description: `DNS auto-create failed: ${dnsError instanceof Error ? dnsError.message : 'Unknown error'}`,
            userId: (await getCurrentUserId())?.toString() || 'system',
            userRole: currentUserRole
          });
        }
      }
    }
    
    await logActivity('APPROVE_APPLICATION', `Menyetujui permohonan ${applicationId}`, currentUserRole);
    
    revalidatePath('/applications');
    revalidatePath(`/applications/${applicationId}`);
    revalidatePath('/domains');
    revalidatePath('/dashboard');
    revalidatePath('/super-admin/dashboard');
    revalidatePath('/audit-trail');

    return { success: true, message: `Permohonan ${applicationId} berhasil disetujui.` };
  } catch (error) {
    console.error('Error approving application:', error);
    return { success: false, message: 'Terjadi kesalahan saat menyetujui permohonan.' };
  }
}

export async function rejectApplication(applicationId: string, reason: string, currentUserRole: User['role']): Promise<{ success: boolean; message: string }> {
  const allowedRoles: User['role'][] = ['Administrator', 'Kepala Bidang', 'Super Admin', 'Pengelola Sistem'];
  if (!allowedRoles.includes(currentUserRole)) {
    return { success: false, message: 'Anda tidak memiliki izin untuk melakukan tindakan ini.' };
  }

  try {
    const application = await getApplicationById(applicationId);
    if (!application) {
        throw new Error('Application not found');
    }

    await updateApplicationStatus(applicationId, 'rejected', reason);
    
    logActivity('REJECT_APPLICATION', `Menolak permohonan ${applicationId} (${application.domainName}). Alasan: ${reason}`, currentUserRole);
    
    revalidatePath('/applications');
    revalidatePath(`/applications/${applicationId}`);
    revalidatePath('/dashboard');
    revalidatePath('/super-admin/dashboard');
    revalidatePath('/audit-trail');

    return { success: true, message: `Permohonan ${applicationId} berhasil ditolak.` };
  } catch (error) {
    console.error('Error rejecting application:', error);
    return { success: false, message: 'Terjadi kesalahan saat menolak permohonan.' };
  }
}
