"use server";

import { revalidatePath } from "next/cache";
import { auditService } from "@/backend/services/audit.service";
import type { Application } from "@/backend/models/types";
import { getCurrentUserId } from "@/backend/utils/auth";
import type { SubdomainApplication, User } from "@/backend/models/types";
import {
  createApplication,
  updateApplicationStatus,
  getApplicationById,
  createDomainFromApplication,
} from "@/backend/services";

type ActionResponse = {
  success: boolean;
  message: string;
};

export async function submitApplication(
  applicationData: Omit<
    SubdomainApplication,
    "id" | "status" | "submittedDate" | "documents"
  >,
  currentUserRole: User["role"]
): Promise<ActionResponse> {
  const { domainName, opd, reason } = applicationData;

  if (!domainName || !opd) {
    return { success: false, message: "Data tidak lengkap." };
  }

  try {
    const newApplication: Application = {
      ...applicationData,
      id: 0, // Will be generated by createApplication
      application_type: "domain",
      opd_id: 0,
      submitter_id: 0,
      status: "Pending" as const,
      submitted_at: new Date().toISOString(),
      submittedDate: new Date().toISOString().split("T")[0],
    };

    const newAppId = await createApplication(newApplication);

    const currentUserId = await getCurrentUserId();

    await auditService.logAction({
      action: "SUBMIT_APPLICATION",
      resourceType: "application",
      resourceId: newAppId,
      description: `Mengajukan permohonan untuk ${domainName}`,
      userId: currentUserId?.toString() || "unknown",
      user: opd,
      userRole: currentUserRole,
    });

    revalidatePath("/applications");
    revalidatePath("/dashboard");
    revalidatePath("/super-admin/dashboard");

    return {
      success: true,
      message: "Permohonan berhasil dikirim untuk ditinjau.",
    };
  } catch (error) {
    console.error("Error submitting application:", error);
    return {
      success: false,
      message: "Terjadi kesalahan pada server saat memproses permohonan.",
    };
  }
}

export async function forwardForApproval(
  applicationId: string,
  currentUserRole: User["role"]
): Promise<{ success: boolean; message: string }> {
  const allowedRoles: User["role"][] = ["Super Admin"];
  if (!allowedRoles.includes(currentUserRole)) {
    return {
      success: false,
      message: "Anda tidak memiliki izin untuk melakukan tindakan ini.",
    };
  }

  try {
    const application = await getApplicationById(applicationId);
    if (!application) {
      throw new Error("Application not found");
    }

    await updateApplicationStatus(applicationId, "Pending");

    await auditService.logAction({
      action: "FORWARD_FOR_APPROVAL",
      resourceType: "application",
      resourceId: applicationId,
      description: `Meneruskan permohonan ${applicationId} (${application.domainName}) untuk persetujuan final.`,
      userId: "system",
      userRole: currentUserRole,
    });

    revalidatePath("/applications");
    revalidatePath(`/applications/${applicationId}`);
    revalidatePath("/super-admin/dashboard");
    revalidatePath("/audit-trail");

    return {
      success: true,
      message: `Permohonan ${applicationId} berhasil diteruskan untuk persetujuan final.`,
    };
  } catch (error) {
    console.error("Error forwarding application:", error);
    return {
      success: false,
      message: "Terjadi kesalahan saat meneruskan permohonan.",
    };
  }
}

export async function approveApplication(
  applicationId: string,
  currentUserRole: User["role"]
): Promise<{ success: boolean; message: string }> {
  const allowedRoles: User["role"][] = ["Super Admin", "Admin Daerah"];
  if (!allowedRoles.includes(currentUserRole)) {
    return {
      success: false,
      message: "Anda tidak memiliki izin untuk melakukan tindakan ini.",
    };
  }

  try {
    console.log(`[approveApplication] Starting approval for application ${applicationId}`);
    
    const application = await getApplicationById(applicationId);
    if (!application) {
      console.error(`[approveApplication] Application ${applicationId} not found`);
      throw new Error("Application not found");
    }
    console.log(`[approveApplication] Application found:`, application.id);

    console.log(`[approveApplication] Updating status to Approved...`);
    await updateApplicationStatus(applicationId, "Approved");
    console.log(`[approveApplication] Status updated successfully`);

    // NOTE: Domain TIDAK langsung dibuat saat application disetujui
    // Domain baru dibuat saat Admin Daerah mengajukan hosting dan hosting disetujui
    // Alur: Application Approved → Admin Daerah pilih hosting → Hosting Approved → Domain dibuat (active)

    console.log(`[approveApplication] Logging activity...`);
    try {
      await auditService.logAction({
        action: "APPROVE_APPLICATION",
        resourceType: "application",
        resourceId: applicationId,
        description: `Menyetujui permohonan ${applicationId}`,
        userId: "system",
        userRole: currentUserRole,
      });
      console.log(`[approveApplication] Activity logged successfully`);
    } catch (logError) {
      console.error(`[approveApplication] Failed to log activity:`, logError);
      // Don't fail the whole operation if logging fails
    }

    console.log(`[approveApplication] Revalidating paths...`);
    revalidatePath("/applications");
    revalidatePath(`/applications/${applicationId}`);
    revalidatePath("/domains");
    revalidatePath("/dashboard");
    revalidatePath("/super-admin/dashboard");
    revalidatePath("/audit-trail");
    console.log(`[approveApplication] Paths revalidated`);

    return {
      success: true,
      message: `Permohonan ${applicationId} berhasil disetujui.`,
    };
  } catch (error) {
    console.error("[approveApplication] Error approving application:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("[approveApplication] Error details:", errorMessage);
    return {
      success: false,
      message: `Terjadi kesalahan saat menyetujui permohonan: ${errorMessage}`,
    };
  }
}

export async function rejectApplication(
  applicationId: string,
  reason: string,
  currentUserRole: User["role"]
): Promise<{ success: boolean; message: string }> {
  const allowedRoles: User["role"][] = ["Super Admin", "Admin Daerah"];
  if (!allowedRoles.includes(currentUserRole)) {
    return {
      success: false,
      message: "Anda tidak memiliki izin untuk melakukan tindakan ini.",
    };
  }

  try {
    console.log(`[rejectApplication] Starting rejection for application ${applicationId}`);
    
    const application = await getApplicationById(applicationId);
    if (!application) {
      console.error(`[rejectApplication] Application ${applicationId} not found`);
      throw new Error("Application not found");
    }
    console.log(`[rejectApplication] Application found:`, application.id);

    console.log(`[rejectApplication] Updating status to Rejected...`);
    await updateApplicationStatus(applicationId, "Rejected", reason);
    console.log(`[rejectApplication] Status updated successfully`);

    console.log(`[rejectApplication] Logging activity...`);
    try {
      await auditService.logAction({
        action: "REJECT_APPLICATION",
        resourceType: "application",
        resourceId: applicationId,
        description: `Menolak permohonan ${applicationId} (${application.domainName}). Alasan: ${reason}`,
        userId: "system",
        userRole: currentUserRole,
      });
      console.log(`[rejectApplication] Activity logged successfully`);
    } catch (logError) {
      console.error(`[rejectApplication] Failed to log activity:`, logError);
      // Don't fail the whole operation if logging fails
    }

    console.log(`[rejectApplication] Revalidating paths...`);
    revalidatePath("/applications");
    revalidatePath(`/applications/${applicationId}`);
    revalidatePath("/dashboard");
    revalidatePath("/super-admin/dashboard");
    revalidatePath("/audit-trail");
    console.log(`[rejectApplication] Paths revalidated`);

    return {
      success: true,
      message: `Permohonan berhasil ditolak.`,
    };
  } catch (error) {
    console.error("[rejectApplication] Error rejecting application:", error);
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("[rejectApplication] Error details:", errorMessage);
    
    // If error is from database connection but status was likely updated, still return success
    if (errorMessage.includes("ECONNREFUSED") || errorMessage.includes("Query failed")) {
      console.log("[rejectApplication] Database error but returning success - status likely updated");
      revalidatePath("/applications");
      revalidatePath(`/applications/${applicationId}`);
      revalidatePath("/dashboard");
      revalidatePath("/super-admin/dashboard");
      return {
        success: true,
        message: "Permohonan berhasil ditolak.",
      };
    }
    
    return {
      success: false,
      message: `Terjadi kesalahan saat menolak permohonan: ${errorMessage}`,
    };
  }
}
