// Safe mock data types to avoid mysql2 conflicts
import type {
  SubdomainApplication,
  User,
  AuditLog,
  HostingApplication,
  UserRole,
  UserStatus,
} from "@/backend/models/types";

interface MockDomain {
  id: string;
  hostname: string;
  status: string;
  expiryDate: string;
  opd: string;
  parentDomain?: string;
  activationDate?: string;
  ttl?: string;
  recordType?: string;
  priority?: string;
  destination?: string;
}

interface MockUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  status: UserStatus;
  nip?: string;
  whatsapp?: string;
  opd?: string;
}

export const MOCK_ROLES = ["Super Admin", "Admin Daerah"];

export const MOCK_OPDS = [
  { id: 1, name: "Dinas Kesehatan" },
  { id: 2, name: "Dinas Pendidikan" },
  { id: 3, name: "Dinas Komunikasi dan Informatika" },
  { id: 4, name: "Dinas Pekerjaan Umum" },
  { id: 5, name: "Dinas Sosial" },
  { id: 6, name: "Dinas Perdagangan" },
  { id: 7, name: "Dinas Perindustrian" },
  { id: 8, name: "Dinas Kebudayaan" },
  { id: 9, name: "Dinas Kepemudaan dan Olahraga" },
  { id: 10, name: "Dinas Perlindungan Anak dan Keluarga Berencana" },
];

export const MOCK_USERS: MockUser[] = [
  {
    id: "user1",
    name: "Ahmad Supardi",
    email: "admin@bandung.go.id",
    role: "Super Admin",
    status: "active",
    nip: "198501012010011001",
    whatsapp: "081234567890",
  },
  {
    id: "user2",
    name: "Siti Nurhaliza",
    email: "diskominfo@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Komunikasi dan Informatika",
    nip: "198702152011012002",
    whatsapp: "081234567891",
  },
  {
    id: "user3",
    name: "Budi Santoso",
    email: "dinkes@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kesehatan",
    nip: "198905202012011003",
    whatsapp: "081234567892",
  },
  {
    id: "user4",
    name: "Dewi Kartika",
    email: "disdik@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pendidikan",
    nip: "199003102013012004",
    whatsapp: "081234567893",
  },
  {
    id: "user5",
    name: "Rudi Hartono",
    email: "dpupr@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pekerjaan Umum",
    nip: "198801252014011005",
    whatsapp: "081234567894",
  },
  {
    id: "user6",
    name: "Linda Kusuma",
    email: "dinsos@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Sosial",
    nip: "199107182015012006",
    whatsapp: "081234567895",
  },
  {
    id: "user7",
    name: "Hendra Wijaya",
    email: "disdag@bandung.go.id",
    role: "Admin Daerah",
    status: "inactive",
    opd: "Dinas Perdagangan",
    nip: "198612302016011007",
    whatsapp: "081234567896",
  },
  {
    id: "user8",
    name: "Maya Sari",
    email: "disperin@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Perindustrian",
    nip: "199204152017012008",
    whatsapp: "081234567897",
  },
  {
    id: "user9",
    name: "Agus Priyanto",
    email: "disbudpar@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kebudayaan",
    nip: "198809222018011009",
    whatsapp: "081234567898",
  },
  {
    id: "user10",
    name: "Rina Andriani",
    email: "dispora@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kepemudaan dan Olahraga",
    nip: "199306282019012010",
    whatsapp: "081234567899",
  },
];

export const MOCK_DOMAINS: MockDomain[] = [
  {
    id: "domain1",
    hostname: "dinkes.bandung.go.id",
    status: "active",
    expiryDate: "2025-12-31",
    opd: "Dinas Kesehatan",
    parentDomain: "bandung.go.id",
    activationDate: "2025-01-15",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.67",
  },
  {
    id: "domain2",
    hostname: "disdik.bandung.go.id",
    status: "active",
    expiryDate: "2025-11-20",
    opd: "Dinas Pendidikan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-11-20",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.68",
  },
  {
    id: "domain3",
    hostname: "diskominfo.bandung.go.id",
    status: "active",
    expiryDate: "2026-03-15",
    opd: "Dinas Komunikasi dan Informatika",
    parentDomain: "bandung.go.id",
    activationDate: "2025-03-15",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.69",
  },
  {
    id: "domain4",
    hostname: "dpupr.bandung.go.id",
    status: "active",
    expiryDate: "2025-08-10",
    opd: "Dinas Pekerjaan Umum",
    parentDomain: "bandung.go.id",
    activationDate: "2024-08-10",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.70",
  },
  {
    id: "domain5",
    hostname: "dinsos.bandung.go.id",
    status: "active",
    expiryDate: "2025-06-25",
    opd: "Dinas Sosial",
    parentDomain: "bandung.go.id",
    activationDate: "2024-06-25",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.71",
  },
  {
    id: "domain6",
    hostname: "disdag.bandung.go.id",
    status: "inactive",
    expiryDate: "2024-12-31",
    opd: "Dinas Perdagangan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-01-01",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.72",
  },
  {
    id: "domain7",
    hostname: "disperin.bandung.go.id",
    status: "active",
    expiryDate: "2025-09-18",
    opd: "Dinas Perindustrian",
    parentDomain: "bandung.go.id",
    activationDate: "2024-09-18",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.73",
  },
  {
    id: "domain8",
    hostname: "disbudpar.bandung.go.id",
    status: "active",
    expiryDate: "2025-10-05",
    opd: "Dinas Kebudayaan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-10-05",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.74",
  },
  {
    id: "domain9",
    hostname: "dispora.bandung.go.id",
    status: "active",
    expiryDate: "2025-07-22",
    opd: "Dinas Kepemudaan dan Olahraga",
    parentDomain: "bandung.go.id",
    activationDate: "2024-07-22",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.75",
  },
  {
    id: "domain10",
    hostname: "ppkb.bandung.go.id",
    status: "expired",
    expiryDate: "2024-05-10",
    opd: "Dinas Perlindungan Anak dan Keluarga Berencana",
    parentDomain: "bandung.go.id",
    activationDate: "2023-05-10",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.76",
  },
  {
    id: "domain11",
    hostname: "ehealth.dinkes.bandung.go.id",
    status: "active",
    expiryDate: "2025-12-15",
    opd: "Dinas Kesehatan",
    parentDomain: "dinkes.bandung.go.id",
    activationDate: "2025-02-10",
    ttl: "3600",
    recordType: "CNAME",
    priority: "10",
    destination: "dinkes.bandung.go.id",
  },
  {
    id: "domain12",
    hostname: "ppdb.disdik.bandung.go.id",
    status: "active",
    expiryDate: "2025-11-01",
    opd: "Dinas Pendidikan",
    parentDomain: "disdik.bandung.go.id",
    activationDate: "2024-11-01",
    ttl: "3600",
    recordType: "CNAME",
    priority: "10",
    destination: "disdik.bandung.go.id",
  },
  {
    id: "domain13",
    hostname: "portal.diskominfo.bandung.go.id",
    status: "active",
    expiryDate: "2026-04-20",
    opd: "Dinas Komunikasi dan Informatika",
    parentDomain: "diskominfo.bandung.go.id",
    activationDate: "2025-04-20",
    ttl: "3600",
    recordType: "CNAME",
    priority: "10",
    destination: "diskominfo.bandung.go.id",
  },
  {
    id: "domain14",
    hostname: "infrastruktur.dpupr.bandung.go.id",
    status: "active",
    expiryDate: "2025-09-05",
    opd: "Dinas Pekerjaan Umum",
    parentDomain: "dpupr.bandung.go.id",
    activationDate: "2024-09-05",
    ttl: "3600",
    recordType: "CNAME",
    priority: "10",
    destination: "dpupr.bandung.go.id",
  },
  {
    id: "domain15",
    hostname: "bantuan.dinsos.bandung.go.id",
    status: "active",
    expiryDate: "2025-07-12",
    opd: "Dinas Sosial",
    parentDomain: "dinsos.bandung.go.id",
    activationDate: "2024-07-12",
    ttl: "3600",
    recordType: "CNAME",
    priority: "10",
    destination: "dinsos.bandung.go.id",
  },
];

export const MOCK_APPLICATIONS: SubdomainApplication[] = [
  {
    id: "app1",
    userId: "user3",
    domainName: "vaksinasi.dinkes.bandung.go.id",
    purpose: "Portal Informasi Vaksinasi COVID-19",
    status: "pending_approval",
    submissionDate: "2025-11-05",
    submittedDate: "2025-11-05",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
    description:
      "Website untuk informasi dan pendaftaran vaksinasi COVID-19 di Kota Bandung",
  },
  {
    id: "app2",
    userId: "user4",
    domainName: "ujian.disdik.bandung.go.id",
    purpose: "Sistem Ujian Online",
    status: "approved",
    submissionDate: "2025-10-20",
    submittedDate: "2025-10-20",
    approvalDate: "2025-10-22",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
    description: "Platform ujian online untuk siswa SMA/SMK di Kota Bandung",
  },
  {
    id: "app3",
    userId: "user2",
    domainName: "smartcity.diskominfo.bandung.go.id",
    purpose: "Dashboard Smart City",
    status: "approved",
    submissionDate: "2025-10-10",
    submittedDate: "2025-10-10",
    approvalDate: "2025-10-12",
    opd: "Dinas Komunikasi dan Informatika",
    applicantName: "Siti Nurhaliza",
    description: "Dashboard monitoring dan kontrol Smart City Bandung",
  },
  {
    id: "app4",
    userId: "user5",
    domainName: "pengaduan.dpupr.bandung.go.id",
    purpose: "Portal Pengaduan Infrastruktur",
    status: "pending_review",
    submissionDate: "2025-11-08",
    submittedDate: "2025-11-08",
    opd: "Dinas Pekerjaan Umum",
    applicantName: "Rudi Hartono",
    description:
      "Website untuk pengaduan masalah infrastruktur jalan dan jembatan",
  },
  {
    id: "app5",
    userId: "user6",
    domainName: "bansos.dinsos.bandung.go.id",
    purpose: "Sistem Informasi Bantuan Sosial",
    status: "rejected",
    submissionDate: "2025-10-15",
    submittedDate: "2025-10-15",
    approvalDate: "2025-10-18",
    opd: "Dinas Sosial",
    applicantName: "Linda Kusuma",
    description: "Portal pendaftaran dan verifikasi penerima bantuan sosial",
    rejectionReason:
      "Nama domain tidak sesuai dengan konvensi penamaan yang ditetapkan",
  },
  {
    id: "app6",
    userId: "user8",
    domainName: "umkm.disperin.bandung.go.id",
    purpose: "Portal UMKM Bandung",
    status: "approved",
    submissionDate: "2025-09-25",
    submittedDate: "2025-09-25",
    approvalDate: "2025-09-27",
    opd: "Dinas Perindustrian",
    applicantName: "Maya Sari",
    description: "Platform promosi dan penjualan produk UMKM Kota Bandung",
  },
  {
    id: "app7",
    userId: "user9",
    domainName: "museum.disbudpar.bandung.go.id",
    purpose: "Virtual Museum Tour",
    status: "pending_approval",
    submissionDate: "2025-11-01",
    submittedDate: "2025-11-01",
    opd: "Dinas Kebudayaan",
    applicantName: "Agus Priyanto",
    description: "Website tur virtual museum-museum di Kota Bandung",
  },
  {
    id: "app8",
    userId: "user10",
    domainName: "event.dispora.bandung.go.id",
    purpose: "Portal Event Olahraga",
    status: "approved",
    submissionDate: "2025-10-05",
    submittedDate: "2025-10-05",
    approvalDate: "2025-10-07",
    opd: "Dinas Kepemudaan dan Olahraga",
    applicantName: "Rina Andriani",
    description:
      "Website informasi dan pendaftaran event olahraga di Kota Bandung",
  },
  {
    id: "app9",
    userId: "user3",
    domainName: "telemedicine.dinkes.bandung.go.id",
    purpose: "Layanan Telemedicine",
    status: "pending_review",
    submissionDate: "2025-11-10",
    submittedDate: "2025-11-10",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
    description:
      "Platform konsultasi kesehatan jarak jauh untuk warga Kota Bandung",
  },
  {
    id: "app10",
    userId: "user4",
    domainName: "perpustakaan.disdik.bandung.go.id",
    purpose: "Perpustakaan Digital",
    status: "rejected",
    submissionDate: "2025-09-15",
    submittedDate: "2025-09-15",
    approvalDate: "2025-09-20",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
    description: "Platform perpustakaan digital untuk akses buku elektronik",
    rejectionReason:
      "Infrastruktur server belum siap untuk mendukung platform ini",
  },
];

export const MOCK_HOSTING_APPLICATIONS: HostingApplication[] = [
  {
    id: "host1",
    userId: "user3",
    applicationName: "E-Health Management System",
    description:
      "Sistem manajemen rekam medis elektronik untuk puskesmas dan rumah sakit di Kota Bandung",
    framework: "Laravel 10",
    domainName: "ehealth.dinkes.bandung.go.id",
    status: "pending_approval",
    submittedDate: "2025-11-05",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
  },
  {
    id: "host2",
    userId: "user4",
    applicationName: "PPDB Online",
    description:
      "Platform penerimaan peserta didik baru online untuk sekolah negeri di Kota Bandung",
    framework: "Next.js 14",
    domainName: "ppdb.disdik.bandung.go.id",
    status: "approved",
    submittedDate: "2025-10-15",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
  },
  {
    id: "host3",
    userId: "user2",
    applicationName: "Smart City Dashboard",
    description:
      "Dashboard monitoring real-time untuk berbagai aspek smart city Bandung",
    framework: "React + Node.js",
    domainName: "dashboard.diskominfo.bandung.go.id",
    status: "approved",
    submittedDate: "2025-09-20",
    opd: "Dinas Komunikasi dan Informatika",
    applicantName: "Siti Nurhaliza",
  },
  {
    id: "host4",
    userId: "user5",
    applicationName: "Sistem Pengaduan Infrastruktur",
    description:
      "Aplikasi untuk melaporkan kerusakan infrastruktur jalan, jembatan, dan fasilitas umum",
    framework: "Django",
    domainName: "lapor.dpupr.bandung.go.id",
    status: "pending_review",
    submittedDate: "2025-11-08",
    opd: "Dinas Pekerjaan Umum",
    applicantName: "Rudi Hartono",
  },
  {
    id: "host5",
    userId: "user6",
    applicationName: "Portal Bantuan Sosial",
    description:
      "Sistem pendaftaran dan verifikasi penerima program bantuan sosial",
    framework: "CodeIgniter 4",
    domainName: "bansos.dinsos.bandung.go.id",
    status: "rejected",
    submittedDate: "2025-10-01",
    opd: "Dinas Sosial",
    applicantName: "Linda Kusuma",
    rejectionReason:
      "Spesifikasi resource yang diminta melebihi kapasitas server yang tersedia",
  },
  {
    id: "host6",
    userId: "user8",
    applicationName: "Marketplace UMKM",
    description: "Platform e-commerce untuk produk UMKM lokal Kota Bandung",
    framework: "WordPress + WooCommerce",
    domainName: "umkm.disperin.bandung.go.id",
    status: "approved",
    submittedDate: "2025-09-10",
    opd: "Dinas Perindustrian",
    applicantName: "Maya Sari",
  },
  {
    id: "host7",
    userId: "user9",
    applicationName: "Virtual Museum Platform",
    description:
      "Platform tur virtual 360 derajat untuk museum dan situs budaya di Bandung",
    framework: "Vue.js + Three.js",
    domainName: "museum.disbudpar.bandung.go.id",
    status: "pending_approval",
    submittedDate: "2025-11-02",
    opd: "Dinas Kebudayaan",
    applicantName: "Agus Priyanto",
  },
  {
    id: "host8",
    userId: "user10",
    applicationName: "Portal Event Olahraga",
    description:
      "Website informasi dan registrasi event olahraga di Kota Bandung",
    framework: "Laravel 10 + Vue.js",
    domainName: "sport.dispora.bandung.go.id",
    status: "approved",
    submittedDate: "2025-09-28",
    opd: "Dinas Kepemudaan dan Olahraga",
    applicantName: "Rina Andriani",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log1",
    timestamp: "2025-11-12T09:15:00Z",
    userId: "user1",
    action: "LOGIN",
    resourceType: "user",
    resourceId: "user1",
    description: "Super Admin masuk ke sistem",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log2",
    timestamp: "2025-11-12T08:00:00Z",
    userId: "user1",
    action: "AKTIVASI DOMAIN",
    resourceType: "domain",
    resourceId: "domain1",
    description: "Mengaktifkan domain dinkes.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log3",
    timestamp: "2025-11-11T07:45:00Z",
    userId: "user3",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app1",
    description: "Mengajukan permohonan domain vaksinasi.dinkes.bandung.go.id",
    user: "Budi Santoso",
    userRole: "Admin Daerah",
  },
  {
    id: "log4",
    timestamp: "2025-11-10T15:30:00Z",
    userId: "user1",
    action: "PERSETUJUAN DOMAIN",
    resourceType: "application",
    resourceId: "app2",
    description: "Menyetujui permohonan domain ujian.disdik.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log5",
    timestamp: "2025-11-10T14:20:00Z",
    userId: "user4",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host2",
    description: "Mengajukan permohonan hosting untuk PPDB Online",
    user: "Dewi Kartika",
    userRole: "Admin Daerah",
  },
  {
    id: "log6",
    timestamp: "2025-11-10T10:15:00Z",
    userId: "user1",
    action: "PENOLAKAN DOMAIN",
    resourceType: "application",
    resourceId: "app5",
    description: "Menolak permohonan domain bansos.dinsos.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log7",
    timestamp: "2025-11-09T16:40:00Z",
    userId: "user2",
    action: "SUSPENSI DOMAIN",
    resourceType: "domain",
    resourceId: "domain5",
    description: "Menangguhkan domain sementara untuk maintenance",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log8",
    timestamp: "2025-11-09T15:20:00Z",
    userId: "user2",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app3",
    description:
      "Mengajukan permohonan domain smartcity.diskominfo.bandung.go.id",
    user: "Siti Nurhaliza",
    userRole: "Admin Daerah",
  },
  {
    id: "log9",
    timestamp: "2025-11-09T11:25:00Z",
    userId: "user1",
    action: "DEAKTIVASI DOMAIN",
    resourceType: "domain",
    resourceId: "domain6",
    description: "Menonaktifkan domain disdag.bandung.go.id secara permanen",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log10",
    timestamp: "2025-11-08T13:50:00Z",
    userId: "user1",
    action: "TAMBAH PENGGUNA",
    resourceType: "user",
    resourceId: "user11",
    description: "Menambahkan pengguna baru: Andi Wijaya (Admin Daerah)",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log11",
    timestamp: "2025-11-08T13:20:00Z",
    userId: "user5",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app4",
    description: "Mengajukan permohonan domain pengaduan.dpupr.bandung.go.id",
    user: "Rudi Hartono",
    userRole: "Admin Daerah",
  },
  {
    id: "log12",
    timestamp: "2025-11-08T09:30:00Z",
    userId: "user1",
    action: "PERSETUJUAN HOSTING",
    resourceType: "hosting",
    resourceId: "host3",
    description: "Menyetujui permohonan hosting Smart City Dashboard",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log13",
    timestamp: "2025-11-07T16:00:00Z",
    userId: "user1",
    action: "UBAH PENGGUNA",
    resourceType: "user",
    resourceId: "user5",
    description: "Mengubah data pengguna: Update email Rudi Hartono",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log14",
    timestamp: "2025-11-07T15:10:00Z",
    userId: "user8",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host6",
    description: "Mengajukan permohonan hosting untuk Marketplace UMKM",
    user: "Maya Sari",
    userRole: "Admin Daerah",
  },
  {
    id: "log15",
    timestamp: "2025-11-07T10:20:00Z",
    userId: "user1",
    action: "PENOLAKAN HOSTING",
    resourceType: "hosting",
    resourceId: "host5",
    description: "Menolak permohonan hosting karena spesifikasi tidak sesuai",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log16",
    timestamp: "2025-11-07T09:00:00Z",
    userId: "user1",
    action: "PERSETUJUAN DOMAIN",
    resourceType: "application",
    resourceId: "app6",
    description: "Menyetujui permohonan domain umkm.disperin.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log17",
    timestamp: "2025-11-06T14:45:00Z",
    userId: "user9",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app7",
    description: "Mengajukan permohonan domain museum.disbudpar.bandung.go.id",
    user: "Agus Priyanto",
    userRole: "Admin Daerah",
  },
  {
    id: "log18",
    timestamp: "2025-11-06T11:30:00Z",
    userId: "user1",
    action: "HAPUS PENGGUNA",
    resourceType: "user",
    resourceId: "user12",
    description: "Menghapus pengguna yang sudah tidak aktif",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log19",
    timestamp: "2025-11-05T17:00:00Z",
    userId: "user3",
    action: "LOGOUT",
    resourceType: "user",
    resourceId: "user3",
    description: "Budi Santoso keluar dari sistem",
    user: "Budi Santoso",
    userRole: "Admin Daerah",
  },
  {
    id: "log20",
    timestamp: "2025-11-05T16:20:00Z",
    userId: "user10",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host8",
    description: "Mengajukan permohonan hosting untuk Portal Event Olahraga",
    user: "Rina Andriani",
    userRole: "Admin Daerah",
  },
  {
    id: "log15",
    timestamp: "2025-11-05T08:15:00Z",
    userId: "user3",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host1",
    description:
      "Mengajukan permohonan hosting untuk E-Health Management System",
    user: "Budi Santoso",
    userRole: "Admin Daerah",
  },
  {
    id: "log16",
    timestamp: "2025-11-04T13:40:00Z",
    userId: "user1",
    action: "PENOLAKAN HOSTING",
    resourceType: "hosting",
    resourceId: "host5",
    description: "Menolak permohonan hosting Portal Bantuan Sosial",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log17",
    timestamp: "2025-11-04T10:25:00Z",
    userId: "user6",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app5",
    description: "Mengajukan permohonan domain bansos.dinsos.bandung.go.id",
    user: "Linda Kusuma",
    userRole: "Admin Daerah",
  },
  {
    id: "log18",
    timestamp: "2025-11-03T15:50:00Z",
    userId: "user1",
    action: "AKTIVASI DOMAIN",
    resourceType: "domain",
    resourceId: "domain3",
    description: "Mengaktifkan domain diskominfo.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log19",
    timestamp: "2025-11-03T09:35:00Z",
    userId: "user4",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app2",
    description: "Mengajukan permohonan domain ujian.disdik.bandung.go.id",
    user: "Dewi Kartika",
    userRole: "Admin Daerah",
  },
  {
    id: "log20",
    timestamp: "2025-11-02T14:15:00Z",
    userId: "user1",
    action: "PERSETUJUAN DOMAIN",
    resourceType: "application",
    resourceId: "app8",
    description: "Menyetujui permohonan domain event.dispora.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
];
