/**
 * Mock Data for Domain Manager System - Kalimantan Barat
 * Aligned with database schema from schema-tables-only.sql
 * Data OPD dan Diskominfo dari Pemerintah Provinsi Kalimantan Barat
 * Updated: November 14, 2025
 */

import type {
  User,
  OPD,
  Application,
  Domain,
  Hosting,
  Document,
  AuditLog,
  Notification,
  MockUser,
  ApplicationType,
  ApplicationStatus,
  DomainStatus,
} from "@/backend/models/types";

// Helper functions to add compatibility aliases
export function addDomainAliases(domain: Domain): Domain {
  return {
    ...domain,
    hostname: domain.domain_name,
    expiryDate: domain.expires_at,
    activationDate: domain.activated_at,
  };
}

export function addApplicationAliases(app: Application): Application {
  // Find related domain for domain applications
  const relatedDomain = MOCK_DOMAINS.find((d) => d.application_id === app.id);
  return {
    ...app,
    submittedDate: app.submitted_at,
    submissionDate: app.submitted_at,
    domainName:
      relatedDomain?.domain_name ||
      `${app.opd?.toLowerCase().replace(/\s+/g, "-")}.kalbarprov.go.id`,
  };
}

export function addUserAliases(user: User): User {
  return {
    ...user,
    name: user.username,
    status: user.is_active ? "active" : "inactive",
  };
}

export const MOCK_ROLES = ["Super Admin", "Admin Daerah"];

// ============= OPDS DATA - KALIMANTAN BARAT =============
export const MOCK_OPDS: OPD[] = [
  {
    id: 1,
    name: "Dinas Komunikasi dan Informatika",
    address: "Jl. Ahmad Yani, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Hartoyo, M.T.",
    phone_number: "0561-736622",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 2,
    name: "Dinas Pendidikan dan Kebudayaan",
    address: "Jl. Letjen Sutoyo, Pontianak, Kalimantan Barat",
    contact_person: "Dr. Sri Wahyuni, M.Pd.",
    phone_number: "0561-735306",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 3,
    name: "Dinas Kesehatan",
    address: "Jl. K. H. Wahid Hasyim No. 249, Pontianak, Kalimantan Barat",
    contact_person: "dr. Harisson, M.Kes., Sp.PD.",
    phone_number: "0561-736711",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 4,
    name: "Dinas Pekerjaan Umum dan Penataan Ruang",
    address: "Jl. Alianyang, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Andi Wijaya, M.T.",
    phone_number: "0561-583440",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 5,
    name: "Dinas Sosial",
    address: "Jl. Dr. Sutomo, Pontianak, Kalimantan Barat",
    contact_person: "Drs. Bambang Suryanto, M.Si.",
    phone_number: "0561-732121",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 6,
    name: "Dinas Tenaga Kerja dan Transmigrasi",
    address: "Jl. Sultan Abdurrahman, Pontianak, Kalimantan Barat",
    contact_person: "Dra. Siti Aminah, M.M.",
    phone_number: "0561-736449",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 7,
    name: "Dinas Perhubungan",
    address: "Jl. Jenderal Urip, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Budiman Santoso, M.T.",
    phone_number: "0561-765521",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 8,
    name: "Dinas Pariwisata",
    address: "Jl. Sidas, Pontianak, Kalimantan Barat",
    contact_person: "Agustinus Teras Narang, S.Sos., M.Si.",
    phone_number: "0561-743415",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 9,
    name: "Dinas Perindustrian dan Perdagangan",
    address: "Jl. A. Yani II, Pontianak, Kalimantan Barat",
    contact_person: "Drs. Hermansyah, M.M.",
    phone_number: "0561-736183",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 10,
    name: "Dinas Pertanian dan Hortikultura",
    address: "Jl. Alianyang KM 10, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Suryadi, M.P.",
    phone_number: "0561-587711",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 11,
    name: "Dinas Perikanan",
    address: "Jl. Alianyang KM 10, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Muhammad Rizki, M.Si.",
    phone_number: "0561-587722",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 12,
    name: "Dinas Kehutanan",
    address: "Jl. Gusti Sulung Lelanang, Pontianak, Kalimantan Barat",
    contact_person: "Dr. Ir. Bambang Heryanto, M.Si.",
    phone_number: "0561-736595",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 13,
    name: "Dinas Lingkungan Hidup",
    address: "Jl. Sultan Hamid II, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Ratna Sari Dewi, M.T.",
    phone_number: "0561-742444",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 14,
    name: "Dinas Energi dan Sumber Daya Mineral",
    address: "Jl. Achmad Yani, Pontianak, Kalimantan Barat",
    contact_person: "Ir. Hadi Purnomo, M.T.",
    phone_number: "0561-736211",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 15,
    name: "Badan Perencanaan Pembangunan Daerah",
    address: "Jl. Letjen Sutoyo, Pontianak, Kalimantan Barat",
    contact_person: "Drs. H. Ahmad Fauzi, M.Si.",
    phone_number: "0561-736519",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 16,
    name: "Badan Kepegawaian Daerah",
    address: "Jl. Ahmad Yani, Pontianak, Kalimantan Barat",
    contact_person: "Dra. Hj. Nurlaila, M.M.",
    phone_number: "0561-736344",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 17,
    name: "Badan Pengelola Keuangan dan Aset Daerah",
    address: "Jl. Letjen Sutoyo, Pontianak, Kalimantan Barat",
    contact_person: "Drs. Hari Kusuma, M.M., Ak.",
    phone_number: "0561-735000",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 18,
    name: "Dinas Pemberdayaan Masyarakat dan Desa",
    address: "Jl. Sultan Abdurrahman, Pontianak, Kalimantan Barat",
    contact_person: "Ir. H. Syamsul Bahri, M.Si.",
    phone_number: "0561-736566",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 19,
    name: "Dinas Kependudukan dan Pencatatan Sipil",
    address: "Jl. Ahmad Yani, Pontianak, Kalimantan Barat",
    contact_person: "Drs. Agus Riyanto, M.Si.",
    phone_number: "0561-742233",
    created_at: "2024-01-15 08:00:00",
  },
  {
    id: 20,
    name: "Satuan Polisi Pamong Praja",
    address: "Jl. Letjen Sutoyo, Pontianak, Kalimantan Barat",
    contact_person: "Drs. H. Yusuf Hidayat, M.M.",
    phone_number: "0561-736455",
    created_at: "2024-01-15 08:00:00",
  },
];

// ============= USERS DATA - KALIMANTAN BARAT =============
export const MOCK_USERS: MockUser[] = [
  {
    id: "1",
    name: "Hartoyo",
    email: "superadmin@kalbarprov.go.id",
    role: "Super Admin",
    status: "active",
    nip: "197805152003121001",
    whatsapp: "081511223344",
    opd: "Dinas Komunikasi dan Informatika",
  },
  {
    id: "2",
    name: "Rina Kusumawati",
    email: "admin.diskominfo@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Komunikasi dan Informatika",
    nip: "198205102005012003",
    whatsapp: "081511223345",
  },
  {
    id: "3",
    name: "Sri Wahyuni",
    email: "admin.disdikbud@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pendidikan dan Kebudayaan",
    nip: "197909252006042002",
    whatsapp: "081511223346",
  },
  {
    id: "4",
    name: "Harisson",
    email: "admin.dinkes@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kesehatan",
    nip: "198103152007011004",
    whatsapp: "081511223347",
  },
  {
    id: "5",
    name: "Andi Wijaya",
    email: "admin.dpupr@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pekerjaan Umum dan Penataan Ruang",
    nip: "197712202008011005",
    whatsapp: "081511223348",
  },
  {
    id: "6",
    name: "Bambang Suryanto",
    email: "admin.dinsos@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Sosial",
    nip: "198006302009011006",
    whatsapp: "081511223349",
  },
  {
    id: "7",
    name: "Siti Aminah",
    email: "admin.disnakertrans@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Tenaga Kerja dan Transmigrasi",
    nip: "198304152010012007",
    whatsapp: "081511223350",
  },
  {
    id: "8",
    name: "Budiman Santoso",
    email: "admin.dishub@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Perhubungan",
    nip: "197808252011011008",
    whatsapp: "081511223351",
  },
  {
    id: "9",
    name: "Agustinus Teras Narang",
    email: "admin.dispar@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pariwisata",
    nip: "198512102012011009",
    whatsapp: "081511223352",
  },
  {
    id: "10",
    name: "Hermansyah",
    email: "admin.disperindag@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Perindustrian dan Perdagangan",
    nip: "198701182013011010",
    whatsapp: "081511223353",
  },
  {
    id: "11",
    name: "Suryadi",
    email: "admin.distanhort@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pertanian dan Hortikultura",
    nip: "197905202014011011",
    whatsapp: "081511223354",
  },
  {
    id: "12",
    name: "Muhammad Rizki",
    email: "admin.diskan@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Perikanan",
    nip: "198808152015011012",
    whatsapp: "081511223355",
  },
  {
    id: "13",
    name: "Bambang Heryanto",
    email: "admin.dishut@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kehutanan",
    nip: "197606252016011013",
    whatsapp: "081511223356",
  },
  {
    id: "14",
    name: "Ratna Sari Dewi",
    email: "admin.dlh@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Lingkungan Hidup",
    nip: "198403102017012014",
    whatsapp: "081511223357",
  },
  {
    id: "15",
    name: "Hadi Purnomo",
    email: "admin.desdm@kalbarprov.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Energi dan Sumber Daya Mineral",
    nip: "197910152018011015",
    whatsapp: "081511223358",
  },
];

// ============= APPLICATIONS DATA - KALIMANTAN BARAT =============
export const MOCK_APPLICATIONS: Application[] = [
  // === APPROVED DOMAIN APPLICATIONS ===
  {
    id: 1,
    application_type: "domain",
    opd_id: 1,
    submitter_id: 2,
    status: "Approved",
    submitted_at: "2024-01-15 09:00:00",
    approved_at: "2024-01-18 10:30:00",
    last_updated_by: 1,
    opd: "Dinas Komunikasi dan Informatika",
    submitter_username: "admin.diskominfo",
    submitter_email: "admin.diskominfo@kalbarprov.go.id",
  },
  {
    id: 2,
    application_type: "domain",
    opd_id: 2,
    submitter_id: 3,
    status: "Approved",
    submitted_at: "2024-02-10 10:15:00",
    approved_at: "2024-02-15 14:00:00",
    last_updated_by: 1,
    opd: "Dinas Pendidikan dan Kebudayaan",
    submitter_username: "admin.disdikbud",
    submitter_email: "admin.disdikbud@kalbarprov.go.id",
  },
  {
    id: 3,
    application_type: "domain",
    opd_id: 3,
    submitter_id: 4,
    status: "Approved",
    submitted_at: "2024-03-05 08:30:00",
    approved_at: "2024-03-10 11:45:00",
    last_updated_by: 1,
    opd: "Dinas Kesehatan",
    submitter_username: "admin.dinkes",
    submitter_email: "admin.dinkes@kalbarprov.go.id",
  },
  {
    id: 4,
    application_type: "domain",
    opd_id: 4,
    submitter_id: 5,
    status: "Approved",
    submitted_at: "2024-03-20 13:00:00",
    approved_at: "2024-03-25 15:30:00",
    last_updated_by: 1,
    opd: "Dinas Pekerjaan Umum dan Penataan Ruang",
    submitter_username: "admin.dpupr",
    submitter_email: "admin.dpupr@kalbarprov.go.id",
  },
  {
    id: 5,
    application_type: "domain",
    opd_id: 5,
    submitter_id: 6,
    status: "Approved",
    submitted_at: "2024-04-08 09:20:00",
    approved_at: "2024-04-12 10:00:00",
    last_updated_by: 1,
    opd: "Dinas Sosial",
    submitter_username: "admin.dinsos",
    submitter_email: "admin.dinsos@kalbarprov.go.id",
  },
  {
    id: 6,
    application_type: "domain",
    opd_id: 8,
    submitter_id: 9,
    status: "Approved",
    submitted_at: "2024-05-15 11:00:00",
    approved_at: "2024-05-20 13:15:00",
    last_updated_by: 1,
    opd: "Dinas Pariwisata",
    submitter_username: "admin.dispar",
    submitter_email: "admin.dispar@kalbarprov.go.id",
  },
  {
    id: 7,
    application_type: "domain",
    opd_id: 10,
    submitter_id: 11,
    status: "Approved",
    submitted_at: "2024-06-20 08:45:00",
    approved_at: "2024-06-25 10:30:00",
    last_updated_by: 1,
    opd: "Dinas Pertanian dan Hortikultura",
    submitter_username: "admin.distanhort",
    submitter_email: "admin.distanhort@kalbarprov.go.id",
  },
  {
    id: 8,
    application_type: "domain",
    opd_id: 11,
    submitter_id: 12,
    status: "Approved",
    submitted_at: "2024-07-10 10:00:00",
    approved_at: "2024-07-15 14:20:00",
    last_updated_by: 1,
    opd: "Dinas Perikanan",
    submitter_username: "admin.diskan",
    submitter_email: "admin.diskan@kalbarprov.go.id",
  },
  {
    id: 9,
    application_type: "domain",
    opd_id: 13,
    submitter_id: 14,
    status: "Approved",
    submitted_at: "2024-08-05 09:30:00",
    approved_at: "2024-08-10 11:00:00",
    last_updated_by: 1,
    opd: "Dinas Lingkungan Hidup",
    submitter_username: "admin.dlh",
    submitter_email: "admin.dlh@kalbarprov.go.id",
  },
  {
    id: 10,
    application_type: "domain",
    opd_id: 15,
    submitter_id: 1,
    status: "Approved",
    submitted_at: "2024-09-01 08:00:00",
    approved_at: "2024-09-05 10:00:00",
    last_updated_by: 1,
    opd: "Badan Perencanaan Pembangunan Daerah",
    submitter_username: "superadmin",
    submitter_email: "superadmin@kalbarprov.go.id",
  },
  // === PENDING DOMAIN APPLICATIONS ===
  {
    id: 11,
    application_type: "domain",
    opd_id: 7,
    submitter_id: 8,
    status: "Pending",
    submitted_at: "2025-11-10 10:30:00",
    opd: "Dinas Perhubungan",
    submitter_username: "admin.dishub",
    submitter_email: "admin.dishub@kalbarprov.go.id",
  },
  {
    id: 12,
    application_type: "domain",
    opd_id: 9,
    submitter_id: 10,
    status: "Pending",
    submitted_at: "2025-11-12 09:15:00",
    opd: "Dinas Perindustrian dan Perdagangan",
    submitter_username: "admin.disperindag",
    submitter_email: "admin.disperindag@kalbarprov.go.id",
  },
  {
    id: 13,
    application_type: "domain",
    opd_id: 6,
    submitter_id: 7,
    status: "Pending",
    submitted_at: "2025-11-13 14:00:00",
    opd: "Dinas Tenaga Kerja dan Transmigrasi",
    submitter_username: "admin.disnakertrans",
    submitter_email: "admin.disnakertrans@kalbarprov.go.id",
  },
  // === REJECTED DOMAIN APPLICATION ===
  {
    id: 14,
    application_type: "domain",
    opd_id: 12,
    submitter_id: 13,
    status: "Rejected",
    reason:
      "Nama domain tidak sesuai dengan konvensi penamaan yang ditetapkan. Gunakan format: [nama-dinas].kalbarprov.go.id",
    submitted_at: "2025-10-20 11:30:00",
    approved_at: "2025-10-25 14:15:00",
    last_updated_by: 1,
    opd: "Dinas Kehutanan",
    submitter_username: "admin.dishut",
    submitter_email: "admin.dishut@kalbarprov.go.id",
  },
  // === APPROVED HOSTING APPLICATIONS ===
  {
    id: 15,
    application_type: "hosting",
    opd_id: 1,
    submitter_id: 2,
    status: "Approved",
    submitted_at: "2024-02-01 10:00:00",
    approved_at: "2024-02-05 13:30:00",
    last_updated_by: 1,
    opd: "Dinas Komunikasi dan Informatika",
    submitter_username: "admin.diskominfo",
    submitter_email: "admin.diskominfo@kalbarprov.go.id",
  },
  {
    id: 16,
    application_type: "hosting",
    opd_id: 2,
    submitter_id: 3,
    status: "Approved",
    submitted_at: "2024-03-15 11:30:00",
    approved_at: "2024-03-20 14:00:00",
    last_updated_by: 1,
    opd: "Dinas Pendidikan dan Kebudayaan",
    submitter_username: "admin.disdikbud",
    submitter_email: "admin.disdikbud@kalbarprov.go.id",
  },
  {
    id: 17,
    application_type: "hosting",
    opd_id: 3,
    submitter_id: 4,
    status: "Approved",
    submitted_at: "2024-04-20 09:00:00",
    approved_at: "2024-04-25 11:30:00",
    last_updated_by: 1,
    opd: "Dinas Kesehatan",
    submitter_username: "admin.dinkes",
    submitter_email: "admin.dinkes@kalbarprov.go.id",
  },
  {
    id: 18,
    application_type: "hosting",
    opd_id: 8,
    submitter_id: 9,
    status: "Approved",
    submitted_at: "2024-06-10 10:15:00",
    approved_at: "2024-06-15 13:45:00",
    last_updated_by: 1,
    opd: "Dinas Pariwisata",
    submitter_username: "admin.dispar",
    submitter_email: "admin.dispar@kalbarprov.go.id",
  },
  {
    id: 19,
    application_type: "hosting",
    opd_id: 10,
    submitter_id: 11,
    status: "Approved",
    submitted_at: "2024-07-25 08:30:00",
    approved_at: "2024-07-30 10:00:00",
    last_updated_by: 1,
    opd: "Dinas Pertanian dan Hortikultura",
    submitter_username: "admin.distanhort",
    submitter_email: "admin.distanhort@kalbarprov.go.id",
  },
  // === PENDING HOSTING APPLICATIONS ===
  {
    id: 20,
    application_type: "hosting",
    opd_id: 11,
    submitter_id: 12,
    status: "Pending",
    submitted_at: "2025-11-11 13:20:00",
    opd: "Dinas Perikanan",
    submitter_username: "admin.diskan",
    submitter_email: "admin.diskan@kalbarprov.go.id",
  },
  {
    id: 21,
    application_type: "hosting",
    opd_id: 13,
    submitter_id: 14,
    status: "Pending",
    submitted_at: "2025-11-13 10:45:00",
    opd: "Dinas Lingkungan Hidup",
    submitter_username: "admin.dlh",
    submitter_email: "admin.dlh@kalbarprov.go.id",
  },
  // === REJECTED HOSTING APPLICATION ===
  {
    id: 22,
    application_type: "hosting",
    opd_id: 4,
    submitter_id: 5,
    status: "Rejected",
    reason:
      "Spesifikasi teknis yang diajukan tidak memenuhi standar minimum untuk aplikasi yang akan di-hosting",
    submitted_at: "2025-10-18 09:00:00",
    approved_at: "2025-10-22 11:30:00",
    last_updated_by: 1,
    opd: "Dinas Pekerjaan Umum dan Penataan Ruang",
    submitter_username: "admin.dpupr",
    submitter_email: "admin.dpupr@kalbarprov.go.id",
  },
];

// ============= DOMAINS DATA - KALIMANTAN BARAT =============
export const MOCK_DOMAINS: Domain[] = [
  {
    id: 1,
    application_id: 1,
    domain_name: "diskominfo.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-01-20 08:00:00",
    expires_at: "2026-01-20 08:00:00",
    opd: "Dinas Komunikasi dan Informatika",
    opd_id: 1,
  },
  {
    id: 2,
    application_id: 2,
    domain_name: "disdikbud.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-02-18 09:00:00",
    expires_at: "2026-02-18 09:00:00",
    opd: "Dinas Pendidikan dan Kebudayaan",
    opd_id: 2,
  },
  {
    id: 3,
    application_id: 3,
    domain_name: "dinkes.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-03-12 10:00:00",
    expires_at: "2026-03-12 10:00:00",
    opd: "Dinas Kesehatan",
    opd_id: 3,
  },
  {
    id: 4,
    application_id: 4,
    domain_name: "dpupr.kalbarprov.go.id",
    status: "Expired",
    activated_at: "2024-03-28 08:30:00",
    expires_at: "2024-03-28 08:30:00",
    opd: "Dinas Pekerjaan Umum dan Penataan Ruang",
    opd_id: 4,
  },
  {
    id: 5,
    application_id: 5,
    domain_name: "dinsos.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-04-15 11:00:00",
    expires_at: "2026-04-15 11:00:00",
    opd: "Dinas Sosial",
    opd_id: 5,
  },
  {
    id: 6,
    application_id: 6,
    domain_name: "dispar.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-05-22 09:30:00",
    expires_at: "2026-05-22 09:30:00",
    opd: "Dinas Pariwisata",
    opd_id: 8,
  },
  {
    id: 7,
    application_id: 7,
    domain_name: "distanhort.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-06-28 10:00:00",
    expires_at: "2026-06-28 10:00:00",
    opd: "Dinas Pertanian dan Hortikultura",
    opd_id: 10,
  },
  {
    id: 8,
    application_id: 8,
    domain_name: "diskan.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-07-18 08:00:00",
    expires_at: "2026-07-18 08:00:00",
    opd: "Dinas Perikanan",
    opd_id: 11,
  },
  {
    id: 9,
    application_id: 9,
    domain_name: "dlh.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-08-12 11:30:00",
    expires_at: "2026-08-12 11:30:00",
    opd: "Dinas Lingkungan Hidup",
    opd_id: 13,
  },
  {
    id: 10,
    application_id: 10,
    domain_name: "bappeda.kalbarprov.go.id",
    status: "Active",
    activated_at: "2024-09-08 09:00:00",
    expires_at: "2026-09-08 09:00:00",
    opd: "Badan Perencanaan Pembangunan Daerah",
    opd_id: 15,
  },
];

// ============= HOSTINGS DATA - KALIMANTAN BARAT =============
export const MOCK_HOSTINGS: Hosting[] = [
  {
    id: 1,
    application_id: 15,
    domain_id: 1,
    storage_capacity: "20GB",
    bandwidth: "200GB/month",
    server_type: "VPS",
    status: "Active",
    activated_at: "2024-02-06 08:30:00",
    domain_name: "diskominfo.kalbarprov.go.id",
    opd: "Dinas Komunikasi dan Informatika",
    // Compatibility fields for UI
    applicationName: "Portal Resmi Diskominfo Kalbar",
    domainName: "diskominfo.kalbarprov.go.id",
    submittedDate: "2024-02-01 10:00:00",
    applicantName: "Rina Kusumawati",
    framework: "Laravel 11",
    description:
      "Portal website resmi Dinas Komunikasi dan Informatika Provinsi Kalimantan Barat yang menyediakan informasi layanan publik, berita teknologi informasi, dan sistem pelaporan online untuk masyarakat Kalbar",
  },
  {
    id: 2,
    application_id: 16,
    domain_id: 2,
    storage_capacity: "30GB",
    bandwidth: "300GB/month",
    server_type: "VPS",
    status: "Active",
    activated_at: "2024-03-22 09:30:00",
    domain_name: "disdikbud.kalbarprov.go.id",
    opd: "Dinas Pendidikan dan Kebudayaan",
    // Compatibility fields for UI
    applicationName: "Sistem PPDB Online Kalbar",
    domainName: "disdikbud.kalbarprov.go.id",
    submittedDate: "2024-03-15 11:30:00",
    applicantName: "Sri Wahyuni",
    framework: "Next.js 14",
    description:
      "Sistem Penerimaan Peserta Didik Baru (PPDB) Online untuk seluruh sekolah di Kalimantan Barat, dilengkapi dengan fitur pendaftaran real-time, verifikasi dokumen digital, dan pengumuman hasil seleksi",
  },
  {
    id: 3,
    application_id: 17,
    domain_id: 3,
    storage_capacity: "25GB",
    bandwidth: "250GB/month",
    server_type: "VPS",
    status: "Active",
    activated_at: "2024-04-28 10:00:00",
    domain_name: "dinkes.kalbarprov.go.id",
    opd: "Dinas Kesehatan",
    // Compatibility fields for UI
    applicationName: "Sistem Informasi Kesehatan Kalbar",
    domainName: "dinkes.kalbarprov.go.id",
    submittedDate: "2024-04-20 09:00:00",
    applicantName: "dr. Harisson",
    framework: "React + Express.js",
    description:
      "Portal layanan kesehatan masyarakat Kalbar meliputi informasi rumah sakit, puskesmas, jadwal posyandu, program imunisasi, dan sistem pendaftaran online untuk layanan kesehatan di seluruh Kalimantan Barat",
  },
  {
    id: 4,
    application_id: 18,
    domain_id: 6,
    storage_capacity: "40GB",
    bandwidth: "400GB/month",
    server_type: "Dedicated Server",
    status: "Active",
    activated_at: "2024-06-18 11:00:00",
    domain_name: "dispar.kalbarprov.go.id",
    opd: "Dinas Pariwisata",
    // Compatibility fields for UI
    applicationName: "Visit Kalimantan Barat",
    domainName: "dispar.kalbarprov.go.id",
    submittedDate: "2024-06-10 10:15:00",
    applicantName: "Agustinus Teras Narang",
    framework: "WordPress + Custom Plugin",
    description:
      "Portal promosi pariwisata Kalimantan Barat yang menampilkan destinasi wisata, budaya lokal, kuliner khas, event pariwisata, paket tour, dan sistem booking online untuk wisatawan domestik dan mancanegara",
  },
  {
    id: 5,
    application_id: 19,
    domain_id: 7,
    storage_capacity: "15GB",
    bandwidth: "150GB/month",
    server_type: "Shared Hosting",
    status: "Active",
    activated_at: "2024-08-02 09:00:00",
    domain_name: "distanhort.kalbarprov.go.id",
    opd: "Dinas Pertanian dan Hortikultura",
    // Compatibility fields for UI
    applicationName: "Portal Agrikultur Kalbar",
    domainName: "distanhort.kalbarprov.go.id",
    submittedDate: "2024-07-25 08:30:00",
    applicantName: "Ir. Suryadi",
    framework: "CodeIgniter 4",
    description:
      "Sistem informasi pertanian dan hortikultura Kalbar yang menyediakan data harga komoditas, panduan budidaya, jadwal tanam, informasi hama penyakit, dan layanan konsultasi online untuk petani",
  },
  {
    id: 6,
    application_id: 20,
    domain_id: 8,
    storage_capacity: "20GB",
    bandwidth: "200GB/month",
    server_type: "VPS",
    status: "Deactivated",
    activated_at: "",
    domain_name: "diskan.kalbarprov.go.id",
    opd: "Dinas Perikanan",
    // Compatibility fields for UI
    applicationName: "Sistem Informasi Perikanan",
    domainName: "diskan.kalbarprov.go.id",
    submittedDate: "2025-11-11 13:20:00",
    applicantName: "Muhammad Rizki",
    framework: "Laravel 11",
    description:
      "Sistem informasi perikanan yang mengelola data nelayan, kapal, hasil tangkapan, dan statistik perikanan di Kalimantan Barat",
  },
  {
    id: 7,
    application_id: 21,
    domain_id: 9,
    storage_capacity: "25GB",
    bandwidth: "250GB/month",
    server_type: "VPS",
    status: "Deactivated",
    activated_at: "",
    domain_name: "dlh.kalbarprov.go.id",
    opd: "Dinas Lingkungan Hidup",
    // Compatibility fields for UI
    applicationName: "Portal Lingkungan Hidup Kalbar",
    domainName: "dlh.kalbarprov.go.id",
    submittedDate: "2025-11-13 10:45:00",
    applicantName: "Ratna Sari Dewi",
    framework: "Next.js 14",
    description:
      "Portal monitoring kualitas lingkungan, pengaduan sampah, dan program penghijauan di Kalimantan Barat",
  },
  {
    id: 8,
    application_id: 12,
    domain_id: 4,
    storage_capacity: "30GB",
    bandwidth: "300GB/month",
    server_type: "VPS",
    status: "Expired",
    activated_at: "2023-01-15 10:00:00",
    domain_name: "dpupr.kalbarprov.go.id",
    opd: "Dinas Pekerjaan Umum dan Penataan Ruang",
    // Compatibility fields for UI
    applicationName: "Sistem Manajemen Proyek DPUPR",
    domainName: "dpupr.kalbarprov.go.id",
    submittedDate: "2023-01-10 08:00:00",
    applicantName: "Andi Wijaya",
    framework: "Laravel 10",
    description:
      "Sistem manajemen proyek pembangunan infrastruktur Kalimantan Barat yang mencakup monitoring progres, laporan keuangan, dan dokumentasi proyek",
  },
];

// ============= DOCUMENTS DATA - KALIMANTAN BARAT =============
export const MOCK_DOCUMENTS: Document[] = [
  // Domain Application Documents
  {
    id: 1,
    application_id: 1,
    file_name: "surat_permohonan_diskominfo_kalbar.pdf",
    file_path: "/uploads/documents/2024/01/surat_permohonan_diskominfo.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-01-15 09:15:00",
  },
  {
    id: 2,
    application_id: 2,
    file_name: "surat_permohonan_disdikbud_kalbar.pdf",
    file_path: "/uploads/documents/2024/02/surat_permohonan_disdikbud.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-02-10 10:30:00",
  },
  {
    id: 3,
    application_id: 3,
    file_name: "surat_permohonan_dinkes_kalbar.pdf",
    file_path: "/uploads/documents/2024/03/surat_permohonan_dinkes.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-03-05 08:45:00",
  },
  {
    id: 4,
    application_id: 6,
    file_name: "surat_permohonan_dispar_kalbar.pdf",
    file_path: "/uploads/documents/2024/05/surat_permohonan_dispar.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-05-15 11:15:00",
  },
  {
    id: 5,
    application_id: 10,
    file_name: "surat_permohonan_bappeda_kalbar.pdf",
    file_path: "/uploads/documents/2024/09/surat_permohonan_bappeda.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-09-01 08:20:00",
  },
  // Hosting Application Documents
  {
    id: 6,
    application_id: 15,
    file_name: "spesifikasi_hosting_diskominfo.pdf",
    file_path: "/uploads/documents/2024/02/spesifikasi_hosting_diskominfo.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-02-01 10:20:00",
  },
  {
    id: 7,
    application_id: 15,
    file_name: "arsitektur_aplikasi_diskominfo.pdf",
    file_path: "/uploads/documents/2024/02/arsitektur_aplikasi_diskominfo.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-02-01 10:25:00",
  },
  {
    id: 8,
    application_id: 16,
    file_name: "spesifikasi_ppdb_online.pdf",
    file_path: "/uploads/documents/2024/03/spesifikasi_ppdb_online.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-03-15 11:45:00",
  },
  {
    id: 9,
    application_id: 17,
    file_name: "spesifikasi_sistem_kesehatan.pdf",
    file_path: "/uploads/documents/2024/04/spesifikasi_sistem_kesehatan.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-04-20 09:15:00",
  },
  {
    id: 10,
    application_id: 18,
    file_name: "proposal_visit_kalbar.pdf",
    file_path: "/uploads/documents/2024/06/proposal_visit_kalbar.pdf",
    file_type: "application/pdf",
    uploaded_at: "2024-06-10 10:30:00",
  },
  // Pending Application Documents
  {
    id: 11,
    application_id: 11,
    file_name: "surat_permohonan_dishub_kalbar.pdf",
    file_path: "/uploads/documents/2025/11/surat_permohonan_dishub.pdf",
    file_type: "application/pdf",
    uploaded_at: "2025-11-10 10:45:00",
  },
  {
    id: 12,
    application_id: 12,
    file_name: "surat_permohonan_disperindag_kalbar.pdf",
    file_path: "/uploads/documents/2025/11/surat_permohonan_disperindag.pdf",
    file_type: "application/pdf",
    uploaded_at: "2025-11-12 09:30:00",
  },
  {
    id: 13,
    application_id: 20,
    file_name: "spesifikasi_aplikasi_perikanan.pdf",
    file_path: "/uploads/documents/2025/11/spesifikasi_aplikasi_perikanan.pdf",
    file_type: "application/pdf",
    uploaded_at: "2025-11-11 13:35:00",
  },
];

// ============= AUDIT LOGS DATA - KALIMANTAN BARAT =============
export const MOCK_AUDIT_LOGS: AuditLog[] = [
  // Domain Application Approvals
  {
    id: 1,
    user_id: 1,
    application_id: 1,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan domain diskominfo.kalbarprov.go.id dari Dinas Komunikasi dan Informatika",
    timestamp: "2024-01-18 10:30:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 2,
    user_id: 1,
    application_id: 2,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan domain disdikbud.kalbarprov.go.id dari Dinas Pendidikan dan Kebudayaan",
    timestamp: "2024-02-15 14:00:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 3,
    user_id: 1,
    application_id: 3,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan domain dinkes.kalbarprov.go.id dari Dinas Kesehatan",
    timestamp: "2024-03-10 11:45:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 4,
    user_id: 1,
    application_id: 6,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan domain dispar.kalbarprov.go.id dari Dinas Pariwisata",
    timestamp: "2024-05-20 13:15:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  // Hosting Application Approvals
  {
    id: 5,
    user_id: 1,
    application_id: 15,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan hosting Portal Resmi Diskominfo Kalbar dengan spesifikasi VPS 20GB",
    timestamp: "2024-02-05 13:30:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 6,
    user_id: 1,
    application_id: 16,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan hosting Sistem PPDB Online Kalbar dengan spesifikasi VPS 30GB",
    timestamp: "2024-03-20 14:00:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 7,
    user_id: 1,
    application_id: 18,
    action: "APPROVE_APPLICATION",
    details:
      "Menyetujui permohonan hosting Visit Kalimantan Barat dengan spesifikasi Dedicated Server 40GB",
    timestamp: "2024-06-15 13:45:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  // Application Rejections
  {
    id: 8,
    user_id: 1,
    application_id: 14,
    action: "REJECT_APPLICATION",
    details:
      "Menolak permohonan domain dari Dinas Kehutanan: Nama domain tidak sesuai konvensi penamaan",
    timestamp: "2025-10-25 14:15:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 9,
    user_id: 1,
    application_id: 22,
    action: "REJECT_APPLICATION",
    details:
      "Menolak permohonan hosting dari DPUPR: Spesifikasi teknis tidak memenuhi standar minimum",
    timestamp: "2025-10-22 11:30:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  // Domain Submissions
  {
    id: 10,
    user_id: 2,
    application_id: 1,
    action: "SUBMIT_APPLICATION",
    details: "Mengajukan permohonan domain diskominfo.kalbarprov.go.id",
    timestamp: "2024-01-15 09:00:00",
    username: "admin.diskominfo",
    user_role: "Admin Daerah",
  },
  {
    id: 11,
    user_id: 3,
    application_id: 2,
    action: "SUBMIT_APPLICATION",
    details: "Mengajukan permohonan domain disdikbud.kalbarprov.go.id",
    timestamp: "2024-02-10 10:15:00",
    username: "admin.disdikbud",
    user_role: "Admin Daerah",
  },
  {
    id: 12,
    user_id: 4,
    application_id: 3,
    action: "SUBMIT_APPLICATION",
    details: "Mengajukan permohonan domain dinkes.kalbarprov.go.id",
    timestamp: "2024-03-05 08:30:00",
    username: "admin.dinkes",
    user_role: "Admin Daerah",
  },
  // Domain Activations
  {
    id: 13,
    user_id: 1,
    action: "ACTIVATE_DOMAIN",
    details:
      "Mengaktifkan domain diskominfo.kalbarprov.go.id dengan masa aktif 2 tahun",
    timestamp: "2024-01-20 08:00:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 14,
    user_id: 1,
    action: "ACTIVATE_DOMAIN",
    details:
      "Mengaktifkan domain disdikbud.kalbarprov.go.id dengan masa aktif 2 tahun",
    timestamp: "2024-02-18 09:00:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 15,
    user_id: 1,
    action: "ACTIVATE_DOMAIN",
    details:
      "Mengaktifkan domain dispar.kalbarprov.go.id untuk portal pariwisata Visit Kalbar",
    timestamp: "2024-05-22 09:30:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  // Hosting Activations
  {
    id: 16,
    user_id: 1,
    action: "ACTIVATE_HOSTING",
    details:
      "Mengaktifkan hosting Portal Resmi Diskominfo Kalbar pada VPS dengan kapasitas 20GB",
    timestamp: "2024-02-06 08:30:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  {
    id: 17,
    user_id: 1,
    action: "ACTIVATE_HOSTING",
    details:
      "Mengaktifkan hosting Sistem PPDB Online pada VPS dengan kapasitas 30GB",
    timestamp: "2024-03-22 09:30:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
  // Recent Activities
  {
    id: 18,
    user_id: 8,
    application_id: 11,
    action: "SUBMIT_APPLICATION",
    details: "Mengajukan permohonan domain untuk Dinas Perhubungan Kalbar",
    timestamp: "2025-11-10 10:30:00",
    username: "admin.dishub",
    user_role: "Admin Daerah",
  },
  {
    id: 19,
    user_id: 10,
    application_id: 12,
    action: "SUBMIT_APPLICATION",
    details:
      "Mengajukan permohonan domain untuk Dinas Perindustrian dan Perdagangan",
    timestamp: "2025-11-12 09:15:00",
    username: "admin.disperindag",
    user_role: "Admin Daerah",
  },
  {
    id: 20,
    user_id: 1,
    action: "LOGIN",
    details: "Super Admin masuk ke sistem Domain Manager Kalimantan Barat",
    timestamp: "2025-11-14 08:00:00",
    username: "superadmin",
    user_role: "Super Admin",
  },
];

// ============= NOTIFICATIONS DATA - KALIMANTAN BARAT =============
export const MOCK_NOTIFICATIONS: Notification[] = [
  // Domain Approval Notifications
  {
    id: 1,
    user_id: 2,
    message:
      "Permohonan domain diskominfo.kalbarprov.go.id telah disetujui oleh Super Admin",
    type: "domain",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 1,
    link: "/applications/1",
    created_at: "2024-01-18 10:35:00",
    read_at: "2024-01-18 11:00:00",
    expires_at: "2026-01-18 10:35:00",
    is_email_sent: true,
  },
  {
    id: 2,
    user_id: 3,
    message:
      "Permohonan domain disdikbud.kalbarprov.go.id telah disetujui dan siap diaktifkan",
    type: "domain",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 2,
    link: "/applications/2",
    created_at: "2024-02-15 14:05:00",
    read_at: "2024-02-15 15:30:00",
    expires_at: "2026-02-15 14:05:00",
    is_email_sent: true,
  },
  {
    id: 3,
    user_id: 9,
    message:
      "Permohonan domain dispar.kalbarprov.go.id telah disetujui untuk portal Visit Kalimantan Barat",
    type: "domain",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 6,
    link: "/applications/6",
    created_at: "2024-05-20 13:20:00",
    read_at: "2024-05-20 14:00:00",
    expires_at: "2026-05-20 13:20:00",
    is_email_sent: true,
  },
  // Hosting Approval Notifications
  {
    id: 4,
    user_id: 2,
    message:
      "Permohonan hosting Portal Resmi Diskominfo Kalbar telah disetujui dengan spesifikasi VPS 20GB",
    type: "hosting",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 15,
    link: "/hosting-applications/15",
    created_at: "2024-02-05 13:35:00",
    read_at: "2024-02-05 14:00:00",
    expires_at: "2026-02-05 13:35:00",
    is_email_sent: true,
  },
  {
    id: 5,
    user_id: 3,
    message: "Hosting Sistem PPDB Online Kalbar telah aktif dan siap digunakan",
    type: "hosting",
    status: "read",
    related_entity_type: "hosting",
    related_entity_id: 2,
    link: "/hosting/2",
    created_at: "2024-03-22 09:35:00",
    read_at: "2024-03-22 10:00:00",
    expires_at: "2026-03-22 09:35:00",
    is_email_sent: true,
  },
  // Domain Expiry Warning Notifications
  {
    id: 6,
    user_id: 2,
    message:
      "Domain diskominfo.kalbarprov.go.id akan kedaluwarsa dalam 90 hari. Segera lakukan perpanjangan",
    type: "perpanjangan",
    status: "unread",
    related_entity_type: "domain",
    related_entity_id: 1,
    link: "/domains/1",
    created_at: "2025-10-22 08:00:00",
    expires_at: "2026-04-22 08:00:00",
    is_email_sent: true,
  },
  {
    id: 7,
    user_id: 3,
    message:
      "Domain disdikbud.kalbarprov.go.id akan kedaluwarsa dalam 90 hari. Harap segera perpanjang domain",
    type: "perpanjangan",
    status: "unread",
    related_entity_type: "domain",
    related_entity_id: 2,
    link: "/domains/2",
    created_at: "2025-11-20 08:00:00",
    expires_at: "2026-05-20 08:00:00",
    is_email_sent: true,
  },
  // Application Rejection Notifications
  {
    id: 8,
    user_id: 13,
    message:
      "Permohonan domain Dinas Kehutanan ditolak. Nama domain tidak sesuai konvensi penamaan",
    type: "domain",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 14,
    link: "/applications/14",
    created_at: "2025-10-25 14:20:00",
    read_at: "2025-10-25 15:00:00",
    expires_at: "2026-04-25 14:20:00",
    is_email_sent: true,
  },
  {
    id: 9,
    user_id: 5,
    message:
      "Permohonan hosting DPUPR ditolak. Spesifikasi teknis tidak memenuhi standar minimum",
    type: "hosting",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 22,
    link: "/hosting-applications/22",
    created_at: "2025-10-22 11:35:00",
    read_at: "2025-10-22 13:00:00",
    expires_at: "2026-04-22 11:35:00",
    is_email_sent: true,
  },
  // Pending Application Notifications for Super Admin
  {
    id: 10,
    user_id: 1,
    message:
      "Ada 3 permohonan domain baru menunggu persetujuan dari Dishub, Disperindag, dan Disnakertrans",
    type: "system",
    status: "unread",
    link: "/applications?status=Pending&type=domain",
    created_at: "2025-11-13 15:00:00",
    expires_at: "2026-05-13 15:00:00",
    is_email_sent: false,
  },
  {
    id: 11,
    user_id: 1,
    message:
      "Ada 2 permohonan hosting menunggu persetujuan dari Dinas Perikanan dan Dinas Lingkungan Hidup",
    type: "system",
    status: "unread",
    link: "/hosting-applications?status=Pending",
    created_at: "2025-11-13 15:05:00",
    expires_at: "2026-05-13 15:05:00",
    is_email_sent: false,
  },
  // Recent Submission Confirmations
  {
    id: 12,
    user_id: 8,
    message:
      "Permohonan domain untuk Dinas Perhubungan telah diterima dan sedang dalam proses review",
    type: "domain",
    status: "read",
    related_entity_type: "application",
    related_entity_id: 11,
    link: "/applications/11",
    created_at: "2025-11-10 10:35:00",
    read_at: "2025-11-10 11:00:00",
    expires_at: "2026-05-10 10:35:00",
    is_email_sent: true,
  },
  {
    id: 13,
    user_id: 12,
    message:
      "Permohonan hosting aplikasi perikanan telah diterima dan sedang dalam proses evaluasi",
    type: "hosting",
    status: "unread",
    related_entity_type: "application",
    related_entity_id: 20,
    link: "/hosting-applications/20",
    created_at: "2025-11-11 13:25:00",
    expires_at: "2026-05-11 13:25:00",
    is_email_sent: true,
  },
  // System Maintenance Notification
  {
    id: 14,
    user_id: 1,
    message:
      "Maintenance server dijadwalkan pada 20 November 2025 pukul 01:00 - 05:00 WIB",
    type: "system",
    status: "unread",
    link: "/settings/maintenance",
    created_at: "2025-11-14 09:00:00",
    expires_at: "2025-11-20 05:00:00",
    is_email_sent: false,
  },
];

// Export with compatibility aliases automatically added
export const MOCK_DOMAINS_WITH_ALIASES = MOCK_DOMAINS.map(addDomainAliases);
export const MOCK_APPLICATIONS_WITH_ALIASES = MOCK_APPLICATIONS.map(
  addApplicationAliases
);

// Export legacy compatibility
export const MOCK_APPLICATIONS_LEGACY = MOCK_APPLICATIONS;
export const MOCK_DOMAINS_LEGACY = MOCK_DOMAINS;
export const MOCK_HOSTING_APPLICATIONS = MOCK_HOSTINGS;
