// Safe mock data types to avoid mysql2 conflicts
import type {
  SubdomainApplication,
  User,
  AuditLog,
  HostingApplication,
  UserRole,
  UserStatus,
} from "@/backend/models/types";

interface MockDomain {
  id: string;
  hostname: string;
  status: string;
  expiryDate: string;
  opd: string;
  parentDomain?: string;
  activationDate?: string;
  ttl?: string;
  recordType?: string;
  priority?: string;
  destination?: string;
}

interface MockUser {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  status: UserStatus;
  nip?: string;
  whatsapp?: string;
  opd?: string;
}

export const MOCK_ROLES = ["Super Admin", "Admin Daerah"];

export const MOCK_OPDS = [
  { id: 1, name: "Dinas Kesehatan" },
  { id: 2, name: "Dinas Pendidikan" },
  { id: 3, name: "Dinas Komunikasi dan Informatika" },
  { id: 4, name: "Dinas Pekerjaan Umum" },
  { id: 5, name: "Dinas Sosial" },
  { id: 6, name: "Dinas Perdagangan" },
  { id: 7, name: "Dinas Perindustrian" },
  { id: 8, name: "Dinas Kebudayaan" },
  { id: 9, name: "Dinas Kepemudaan dan Olahraga" },
  { id: 10, name: "Dinas Perlindungan Anak dan Keluarga Berencana" },
];

export const MOCK_USERS: MockUser[] = [
  {
    id: "user1",
    name: "Ahmad Supardi",
    email: "admin@bandung.go.id",
    role: "Super Admin",
    status: "active",
    nip: "198501012010011001",
    whatsapp: "081234567890",
  },
  {
    id: "user2",
    name: "Siti Nurhaliza",
    email: "diskominfo@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Komunikasi dan Informatika",
    nip: "198702152011012002",
    whatsapp: "081234567891",
  },
  {
    id: "user3",
    name: "Budi Santoso",
    email: "dinkes@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kesehatan",
    nip: "198905202012011003",
    whatsapp: "081234567892",
  },
  {
    id: "user4",
    name: "Dewi Kartika",
    email: "disdik@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pendidikan",
    nip: "199003102013012004",
    whatsapp: "081234567893",
  },
  {
    id: "user5",
    name: "Rudi Hartono",
    email: "dpupr@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Pekerjaan Umum",
    nip: "198801252014011005",
    whatsapp: "081234567894",
  },
  {
    id: "user6",
    name: "Linda Kusuma",
    email: "dinsos@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Sosial",
    nip: "199107182015012006",
    whatsapp: "081234567895",
  },
  {
    id: "user7",
    name: "Hendra Wijaya",
    email: "disdag@bandung.go.id",
    role: "Admin Daerah",
    status: "inactive",
    opd: "Dinas Perdagangan",
    nip: "198612302016011007",
    whatsapp: "081234567896",
  },
  {
    id: "user8",
    name: "Maya Sari",
    email: "disperin@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Perindustrian",
    nip: "199204152017012008",
    whatsapp: "081234567897",
  },
  {
    id: "user9",
    name: "Agus Priyanto",
    email: "disbudpar@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kebudayaan",
    nip: "198809222018011009",
    whatsapp: "081234567898",
  },
  {
    id: "user10",
    name: "Rina Andriani",
    email: "dispora@bandung.go.id",
    role: "Admin Daerah",
    status: "active",
    opd: "Dinas Kepemudaan dan Olahraga",
    nip: "199306282019012010",
    whatsapp: "081234567899",
  },
];

export const MOCK_DOMAINS: MockDomain[] = [
  // Dinas Kesehatan - 1 active domain (hosted)
  {
    id: "domain1",
    hostname: "dinkes.bandung.go.id",
    status: "active",
    expiryDate: "2025-12-31",
    opd: "Dinas Kesehatan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-11-01",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.67",
  },
  // Dinas Pendidikan - 1 active domain (hosted)
  {
    id: "domain2",
    hostname: "disdik.bandung.go.id",
    status: "active",
    expiryDate: "2025-11-20",
    opd: "Dinas Pendidikan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-10-15",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.68",
  },
  // Dinas Komunikasi dan Informatika - 1 active domain (hosted)
  {
    id: "domain3",
    hostname: "diskominfo.bandung.go.id",
    status: "active",
    expiryDate: "2026-03-15",
    opd: "Dinas Komunikasi dan Informatika",
    parentDomain: "bandung.go.id",
    activationDate: "2024-09-20",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.69",
  },
  // Dinas Pekerjaan Umum - 1 active domain (hosted)
  {
    id: "domain4",
    hostname: "dpupr.bandung.go.id",
    status: "active",
    expiryDate: "2025-08-10",
    opd: "Dinas Pekerjaan Umum",
    parentDomain: "bandung.go.id",
    activationDate: "2024-08-10",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.70",
  },
  // Dinas Sosial - 1 active domain (hosted)
  {
    id: "domain5",
    hostname: "dinsos.bandung.go.id",
    status: "active",
    expiryDate: "2025-06-25",
    opd: "Dinas Sosial",
    parentDomain: "bandung.go.id",
    activationDate: "2024-06-25",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.71",
  },
  // Dinas Perdagangan - 1 inactive domain (intentionally disabled)
  {
    id: "domain6",
    hostname: "disdag.bandung.go.id",
    status: "inactive",
    expiryDate: "2026-12-31",
    opd: "Dinas Perdagangan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-01-01",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.72",
  },
  // Dinas Perindustrian - 1 active domain (hosted)
  {
    id: "domain7",
    hostname: "disperin.bandung.go.id",
    status: "active",
    expiryDate: "2025-09-18",
    opd: "Dinas Perindustrian",
    parentDomain: "bandung.go.id",
    activationDate: "2024-09-10",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.73",
  },
  // Dinas Kebudayaan - 1 active domain (hosted)
  {
    id: "domain8",
    hostname: "disbudpar.bandung.go.id",
    status: "active",
    expiryDate: "2025-10-05",
    opd: "Dinas Kebudayaan",
    parentDomain: "bandung.go.id",
    activationDate: "2024-10-05",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.74",
  },
  // Dinas Kepemudaan dan Olahraga - 1 active domain (hosted)
  {
    id: "domain9",
    hostname: "dispora.bandung.go.id",
    status: "active",
    expiryDate: "2025-07-22",
    opd: "Dinas Kepemudaan dan Olahraga",
    parentDomain: "bandung.go.id",
    activationDate: "2024-09-28",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.75",
  },
  // Dinas Perlindungan Anak dan Keluarga Berencana - 1 expired domain
  {
    id: "domain10",
    hostname: "ppkb.bandung.go.id",
    status: "expired",
    expiryDate: "2024-05-10",
    opd: "Dinas Perlindungan Anak dan Keluarga Berencana",
    parentDomain: "bandung.go.id",
    activationDate: "2023-05-10",
    ttl: "3600",
    recordType: "A",
    priority: "10",
    destination: "103.23.45.76",
  },
];

export const MOCK_APPLICATIONS: SubdomainApplication[] = [
  // === APPROVED - Already hosted (has corresponding domain) ===
  {
    id: "app1",
    userId: "user3",
    domainName: "dinkes.bandung.go.id",
    purpose: "Website Resmi Dinas Kesehatan",
    status: "approved",
    submissionDate: "2024-10-15",
    submittedDate: "2024-10-15",
    approvalDate: "2024-10-20",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
    description: "Portal resmi Dinas Kesehatan Kota Bandung",
  },
  {
    id: "app2",
    userId: "user4",
    domainName: "disdik.bandung.go.id",
    purpose: "Website Resmi Dinas Pendidikan",
    status: "approved",
    submissionDate: "2024-10-01",
    submittedDate: "2024-10-01",
    approvalDate: "2024-10-05",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
    description: "Portal resmi Dinas Pendidikan Kota Bandung",
  },
  {
    id: "app3",
    userId: "user2",
    domainName: "diskominfo.bandung.go.id",
    purpose: "Website Resmi Diskominfo",
    status: "approved",
    submissionDate: "2024-09-10",
    submittedDate: "2024-09-10",
    approvalDate: "2024-09-12",
    opd: "Dinas Komunikasi dan Informatika",
    applicantName: "Siti Nurhaliza",
    description: "Portal resmi Dinas Komunikasi dan Informatika Kota Bandung",
  },
  {
    id: "app4",
    userId: "user5",
    domainName: "dpupr.bandung.go.id",
    purpose: "Website Resmi DPUPR",
    status: "approved",
    submissionDate: "2024-07-25",
    submittedDate: "2024-07-25",
    approvalDate: "2024-07-30",
    opd: "Dinas Pekerjaan Umum",
    applicantName: "Rudi Hartono",
    description: "Portal resmi Dinas Pekerjaan Umum dan Penataan Ruang",
  },
  {
    id: "app5",
    userId: "user6",
    domainName: "dinsos.bandung.go.id",
    purpose: "Website Resmi Dinas Sosial",
    status: "approved",
    submissionDate: "2024-06-10",
    submittedDate: "2024-06-10",
    approvalDate: "2024-06-15",
    opd: "Dinas Sosial",
    applicantName: "Linda Kusuma",
    description: "Portal resmi Dinas Sosial Kota Bandung",
  },
  {
    id: "app6",
    userId: "user7",
    domainName: "disdag.bandung.go.id",
    purpose: "Website Resmi Dinas Perdagangan",
    status: "approved",
    submissionDate: "2023-12-15",
    submittedDate: "2023-12-15",
    approvalDate: "2023-12-20",
    opd: "Dinas Perdagangan",
    applicantName: "Hendra Wijaya",
    description: "Portal resmi Dinas Perdagangan Kota Bandung",
  },
  {
    id: "app7",
    userId: "user8",
    domainName: "disperin.bandung.go.id",
    purpose: "Website Resmi Dinas Perindustrian",
    status: "approved",
    submissionDate: "2024-09-01",
    submittedDate: "2024-09-01",
    approvalDate: "2024-09-05",
    opd: "Dinas Perindustrian",
    applicantName: "Maya Sari",
    description: "Portal resmi Dinas Perindustrian Kota Bandung",
  },
  {
    id: "app8",
    userId: "user9",
    domainName: "disbudpar.bandung.go.id",
    purpose: "Website Resmi Dinas Kebudayaan",
    status: "approved",
    submissionDate: "2024-09-20",
    submittedDate: "2024-09-20",
    approvalDate: "2024-09-25",
    opd: "Dinas Kebudayaan",
    applicantName: "Agus Priyanto",
    description: "Portal resmi Dinas Kebudayaan dan Pariwisata",
  },
  {
    id: "app9",
    userId: "user10",
    domainName: "dispora.bandung.go.id",
    purpose: "Website Resmi Dispora",
    status: "approved",
    submissionDate: "2024-09-15",
    submittedDate: "2024-09-15",
    approvalDate: "2024-09-20",
    opd: "Dinas Kepemudaan dan Olahraga",
    applicantName: "Rina Andriani",
    description: "Portal resmi Dinas Kepemudaan dan Olahraga",
  },
  {
    id: "app10",
    userId: "user3",
    domainName: "ppkb.bandung.go.id",
    purpose: "Website Resmi PPKB",
    status: "approved",
    submissionDate: "2023-04-20",
    submittedDate: "2023-04-20",
    approvalDate: "2023-04-25",
    opd: "Dinas Perlindungan Anak dan Keluarga Berencana",
    applicantName: "Budi Santoso",
    description: "Portal resmi Dinas PPKB",
  },
  // === PENDING APPROVAL - Waiting for Super Admin approval ===
  {
    id: "app11",
    userId: "user3",
    domainName: "vaksinasi.dinkes.bandung.go.id",
    purpose: "Portal Informasi Vaksinasi",
    status: "pending_approval",
    submissionDate: "2025-11-10",
    submittedDate: "2025-11-10",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
    description: "Website untuk informasi dan pendaftaran vaksinasi",
  },
  {
    id: "app12",
    userId: "user4",
    domainName: "ppdb.disdik.bandung.go.id",
    purpose: "PPDB Online",
    status: "pending_approval",
    submissionDate: "2025-11-08",
    submittedDate: "2025-11-08",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
    description: "Platform penerimaan peserta didik baru online",
  },
  // === PENDING REVIEW - Submitted, waiting for initial review ===
  {
    id: "app13",
    userId: "user2",
    domainName: "smartcity.diskominfo.bandung.go.id",
    purpose: "Dashboard Smart City",
    status: "pending_review",
    submissionDate: "2025-11-11",
    submittedDate: "2025-11-11",
    opd: "Dinas Komunikasi dan Informatika",
    applicantName: "Siti Nurhaliza",
    description: "Dashboard monitoring real-time Smart City Bandung",
  },
  // === REJECTED - Declined with reason ===
  {
    id: "app14",
    userId: "user6",
    domainName: "bansos.dinsos.bandung.go.id",
    purpose: "Portal Bantuan Sosial",
    status: "rejected",
    submissionDate: "2025-10-20",
    submittedDate: "2025-10-20",
    approvalDate: "2025-10-25",
    opd: "Dinas Sosial",
    applicantName: "Linda Kusuma",
    description: "Sistem pendaftaran bantuan sosial",
    rejectionReason:
      "Nama domain tidak sesuai dengan konvensi penamaan yang ditetapkan. Gunakan nama yang lebih spesifik.",
  },
];

export const MOCK_HOSTING_APPLICATIONS: HostingApplication[] = [
  // === APPROVED - Already created domain (status: active/inactive/expired) ===
  {
    id: "host1",
    userId: "user3",
    applicationName: "Website Dinas Kesehatan",
    description: "Portal resmi Dinas Kesehatan Kota Bandung",
    framework: "Laravel 10",
    domainName: "dinkes.bandung.go.id",
    status: "approved",
    submittedDate: "2024-10-25",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
  },
  {
    id: "host2",
    userId: "user4",
    applicationName: "Website Dinas Pendidikan",
    description: "Portal resmi Dinas Pendidikan Kota Bandung",
    framework: "Next.js 14",
    domainName: "disdik.bandung.go.id",
    status: "approved",
    submittedDate: "2024-10-10",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
  },
  {
    id: "host3",
    userId: "user2",
    applicationName: "Website Diskominfo",
    description: "Portal resmi Dinas Komunikasi dan Informatika",
    framework: "React + Node.js",
    domainName: "diskominfo.bandung.go.id",
    status: "approved",
    submittedDate: "2024-09-15",
    opd: "Dinas Komunikasi dan Informatika",
    applicantName: "Siti Nurhaliza",
  },
  {
    id: "host4",
    userId: "user5",
    applicationName: "Website DPUPR",
    description: "Portal resmi Dinas Pekerjaan Umum dan Penataan Ruang",
    framework: "Django",
    domainName: "dpupr.bandung.go.id",
    status: "approved",
    submittedDate: "2024-08-05",
    opd: "Dinas Pekerjaan Umum",
    applicantName: "Rudi Hartono",
  },
  {
    id: "host5",
    userId: "user6",
    applicationName: "Website Dinas Sosial",
    description: "Portal resmi Dinas Sosial Kota Bandung",
    framework: "CodeIgniter 4",
    domainName: "dinsos.bandung.go.id",
    status: "approved",
    submittedDate: "2024-06-20",
    opd: "Dinas Sosial",
    applicantName: "Linda Kusuma",
  },
  {
    id: "host6",
    userId: "user7",
    applicationName: "Website Dinas Perdagangan",
    description: "Portal resmi Dinas Perdagangan Kota Bandung (Inactive)",
    framework: "WordPress",
    domainName: "disdag.bandung.go.id",
    status: "approved",
    submittedDate: "2023-12-25",
    opd: "Dinas Perdagangan",
    applicantName: "Hendra Wijaya",
  },
  {
    id: "host7",
    userId: "user8",
    applicationName: "Website Dinas Perindustrian",
    description: "Portal resmi Dinas Perindustrian Kota Bandung",
    framework: "WordPress + WooCommerce",
    domainName: "disperin.bandung.go.id",
    status: "approved",
    submittedDate: "2024-09-05",
    opd: "Dinas Perindustrian",
    applicantName: "Maya Sari",
  },
  {
    id: "host8",
    userId: "user9",
    applicationName: "Website Dinas Kebudayaan",
    description: "Portal resmi Dinas Kebudayaan dan Pariwisata",
    framework: "Vue.js + Three.js",
    domainName: "disbudpar.bandung.go.id",
    status: "approved",
    submittedDate: "2024-10-01",
    opd: "Dinas Kebudayaan",
    applicantName: "Agus Priyanto",
  },
  {
    id: "host9",
    userId: "user10",
    applicationName: "Website Dispora",
    description: "Portal resmi Dinas Kepemudaan dan Olahraga",
    framework: "Laravel 10 + Vue.js",
    domainName: "dispora.bandung.go.id",
    status: "approved",
    submittedDate: "2024-09-25",
    opd: "Dinas Kepemudaan dan Olahraga",
    applicantName: "Rina Andriani",
  },
  {
    id: "host10",
    userId: "user3",
    applicationName: "Website PPKB (Expired)",
    description: "Portal resmi Dinas PPKB (Domain expired)",
    framework: "Laravel 9",
    domainName: "ppkb.bandung.go.id",
    status: "approved",
    submittedDate: "2023-05-01",
    opd: "Dinas Perlindungan Anak dan Keluarga Berencana",
    applicantName: "Budi Santoso",
  },
  // === PENDING APPROVAL - Waiting for Super Admin to approve hosting ===
  {
    id: "host11",
    userId: "user3",
    applicationName: "Portal Vaksinasi",
    description: "Website untuk informasi dan pendaftaran vaksinasi",
    framework: "React + Express",
    domainName: "vaksinasi.dinkes.bandung.go.id",
    status: "pending_approval",
    submittedDate: "2025-11-10",
    opd: "Dinas Kesehatan",
    applicantName: "Budi Santoso",
  },
  {
    id: "host12",
    userId: "user4",
    applicationName: "PPDB Online",
    description: "Platform penerimaan peserta didik baru online",
    framework: "Next.js 15",
    domainName: "ppdb.disdik.bandung.go.id",
    status: "pending_approval",
    submittedDate: "2025-11-09",
    opd: "Dinas Pendidikan",
    applicantName: "Dewi Kartika",
  },
  // === PENDING REVIEW - Submitted, initial review ===
  {
    id: "host13",
    userId: "user2",
    applicationName: "Smart City Dashboard",
    description: "Dashboard monitoring real-time Smart City Bandung",
    framework: "Vue.js + FastAPI",
    domainName: "smartcity.diskominfo.bandung.go.id",
    status: "pending_review",
    submittedDate: "2025-11-11",
    opd: "Dinas Komunikasi dan Informatika",
    applicantName: "Siti Nurhaliza",
  },
  // === REJECTED - Declined with reason ===
  {
    id: "host14",
    userId: "user6",
    applicationName: "Portal Bantuan Sosial",
    description: "Sistem pendaftaran bantuan sosial",
    framework: "CodeIgniter 4",
    domainName: "bansos.dinsos.bandung.go.id",
    status: "rejected",
    submittedDate: "2025-10-22",
    opd: "Dinas Sosial",
    applicantName: "Linda Kusuma",
    rejectionReason:
      "Spesifikasi resource yang diminta melebihi kapasitas server yang tersedia. Silakan kurangi requirement atau gunakan hosting eksternal.",
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log1",
    timestamp: "2025-11-12T09:15:00Z",
    userId: "user1",
    action: "LOGIN",
    resourceType: "user",
    resourceId: "user1",
    description: "Super Admin masuk ke sistem",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log2",
    timestamp: "2025-11-12T08:00:00Z",
    userId: "user1",
    action: "AKTIVASI DOMAIN",
    resourceType: "domain",
    resourceId: "domain1",
    description: "Mengaktifkan domain dinkes.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log3",
    timestamp: "2025-11-11T07:45:00Z",
    userId: "user3",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app1",
    description: "Mengajukan permohonan domain vaksinasi.dinkes.bandung.go.id",
    user: "Budi Santoso",
    userRole: "Admin Daerah",
  },
  {
    id: "log4",
    timestamp: "2025-11-10T15:30:00Z",
    userId: "user1",
    action: "PERSETUJUAN DOMAIN",
    resourceType: "application",
    resourceId: "app2",
    description: "Menyetujui permohonan domain ujian.disdik.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log5",
    timestamp: "2025-11-10T14:20:00Z",
    userId: "user4",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host2",
    description: "Mengajukan permohonan hosting untuk PPDB Online",
    user: "Dewi Kartika",
    userRole: "Admin Daerah",
  },
  {
    id: "log6",
    timestamp: "2025-11-10T10:15:00Z",
    userId: "user1",
    action: "PENOLAKAN DOMAIN",
    resourceType: "application",
    resourceId: "app5",
    description: "Menolak permohonan domain bansos.dinsos.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log7",
    timestamp: "2025-11-09T16:40:00Z",
    userId: "user2",
    action: "SUSPENSI DOMAIN",
    resourceType: "domain",
    resourceId: "domain5",
    description: "Menangguhkan domain sementara untuk maintenance",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log8",
    timestamp: "2025-11-09T15:20:00Z",
    userId: "user2",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app3",
    description:
      "Mengajukan permohonan domain smartcity.diskominfo.bandung.go.id",
    user: "Siti Nurhaliza",
    userRole: "Admin Daerah",
  },
  {
    id: "log9",
    timestamp: "2025-11-09T11:25:00Z",
    userId: "user1",
    action: "DEAKTIVASI DOMAIN",
    resourceType: "domain",
    resourceId: "domain6",
    description: "Menonaktifkan domain disdag.bandung.go.id secara permanen",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log10",
    timestamp: "2025-11-08T13:50:00Z",
    userId: "user1",
    action: "TAMBAH PENGGUNA",
    resourceType: "user",
    resourceId: "user11",
    description: "Menambahkan pengguna baru: Andi Wijaya (Admin Daerah)",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log11",
    timestamp: "2025-11-08T13:20:00Z",
    userId: "user5",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app4",
    description: "Mengajukan permohonan domain pengaduan.dpupr.bandung.go.id",
    user: "Rudi Hartono",
    userRole: "Admin Daerah",
  },
  {
    id: "log12",
    timestamp: "2025-11-08T09:30:00Z",
    userId: "user1",
    action: "PERSETUJUAN HOSTING",
    resourceType: "hosting",
    resourceId: "host3",
    description: "Menyetujui permohonan hosting Smart City Dashboard",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log13",
    timestamp: "2025-11-07T16:00:00Z",
    userId: "user1",
    action: "UBAH PENGGUNA",
    resourceType: "user",
    resourceId: "user5",
    description: "Mengubah data pengguna: Update email Rudi Hartono",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log14",
    timestamp: "2025-11-07T15:10:00Z",
    userId: "user8",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host6",
    description: "Mengajukan permohonan hosting untuk Marketplace UMKM",
    user: "Maya Sari",
    userRole: "Admin Daerah",
  },
  {
    id: "log15",
    timestamp: "2025-11-07T10:20:00Z",
    userId: "user1",
    action: "PENOLAKAN HOSTING",
    resourceType: "hosting",
    resourceId: "host5",
    description: "Menolak permohonan hosting karena spesifikasi tidak sesuai",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log16",
    timestamp: "2025-11-07T09:00:00Z",
    userId: "user1",
    action: "PERSETUJUAN DOMAIN",
    resourceType: "application",
    resourceId: "app6",
    description: "Menyetujui permohonan domain umkm.disperin.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log17",
    timestamp: "2025-11-06T14:45:00Z",
    userId: "user9",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app7",
    description: "Mengajukan permohonan domain museum.disbudpar.bandung.go.id",
    user: "Agus Priyanto",
    userRole: "Admin Daerah",
  },
  {
    id: "log18",
    timestamp: "2025-11-06T11:30:00Z",
    userId: "user1",
    action: "HAPUS PENGGUNA",
    resourceType: "user",
    resourceId: "user12",
    description: "Menghapus pengguna yang sudah tidak aktif",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log19",
    timestamp: "2025-11-05T17:00:00Z",
    userId: "user3",
    action: "LOGOUT",
    resourceType: "user",
    resourceId: "user3",
    description: "Budi Santoso keluar dari sistem",
    user: "Budi Santoso",
    userRole: "Admin Daerah",
  },
  {
    id: "log20",
    timestamp: "2025-11-05T16:20:00Z",
    userId: "user10",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host8",
    description: "Mengajukan permohonan hosting untuk Portal Event Olahraga",
    user: "Rina Andriani",
    userRole: "Admin Daerah",
  },
  {
    id: "log15",
    timestamp: "2025-11-05T08:15:00Z",
    userId: "user3",
    action: "PERMOHONAN HOSTING",
    resourceType: "hosting",
    resourceId: "host1",
    description:
      "Mengajukan permohonan hosting untuk E-Health Management System",
    user: "Budi Santoso",
    userRole: "Admin Daerah",
  },
  {
    id: "log16",
    timestamp: "2025-11-04T13:40:00Z",
    userId: "user1",
    action: "PENOLAKAN HOSTING",
    resourceType: "hosting",
    resourceId: "host5",
    description: "Menolak permohonan hosting Portal Bantuan Sosial",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log17",
    timestamp: "2025-11-04T10:25:00Z",
    userId: "user6",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app5",
    description: "Mengajukan permohonan domain bansos.dinsos.bandung.go.id",
    user: "Linda Kusuma",
    userRole: "Admin Daerah",
  },
  {
    id: "log18",
    timestamp: "2025-11-03T15:50:00Z",
    userId: "user1",
    action: "AKTIVASI DOMAIN",
    resourceType: "domain",
    resourceId: "domain3",
    description: "Mengaktifkan domain diskominfo.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
  {
    id: "log19",
    timestamp: "2025-11-03T09:35:00Z",
    userId: "user4",
    action: "PERMOHONAN DOMAIN",
    resourceType: "application",
    resourceId: "app2",
    description: "Mengajukan permohonan domain ujian.disdik.bandung.go.id",
    user: "Dewi Kartika",
    userRole: "Admin Daerah",
  },
  {
    id: "log20",
    timestamp: "2025-11-02T14:15:00Z",
    userId: "user1",
    action: "PERSETUJUAN DOMAIN",
    resourceType: "application",
    resourceId: "app8",
    description: "Menyetujui permohonan domain event.dispora.bandung.go.id",
    user: "Ahmad Supardi",
    userRole: "Super Admin",
  },
];
